import type { Lesson, LessonPracticeBlock, Quiz } from "@/domain/types";
import { checkpointQuiz, proofLesson } from "../python/shared";

// Secure Software track. Mirrors the python/level-N.ts split: this file owns the
// track's lessons and quizzes, and the shared builders in
// src/content/python/shared.ts do the rest.

const securitySecretPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const settings = ['PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'];\nconsole.log(settings);",
    expectedOutput: "PUBLIC_SUPABASE_URL is public config; SUPABASE_SERVICE_ROLE_KEY is secret.",
    checkYourAnswer: "The word public is not magic, but service role power is. Classify by what the value can do if leaked."
  },
  {
    starterCode: "const boundary = { operation: 'read user profile', enforcedAt: 'client' };\nconsole.log(boundary.enforcedAt);",
    expectedOutput: "client is the wrong boundary for authorization.",
    checkYourAnswer: "Client checks can improve UX, but server or database policy must enforce access before data is returned."
  },
  {
    starterCode: "const env = { MAP_TILE_URL: 'https://tiles.example.com', DATABASE_URL: 'postgres://secret' };\nconsole.log(Object.keys(env));",
    expectedOutput: "MAP_TILE_URL can be public; DATABASE_URL must not be bundled.",
    checkYourAnswer: "Ask whether the value only points at a public resource or whether it grants private access."
  }
];

const securityAccessControlPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const request = { userId: 'u1', resourceOwnerId: 'u1' };\nfunction canReadProfile(req) {\n  return true;\n}\nconsole.log(canReadProfile(request));",
    expectedOutput: "true because the requester owns the profile.",
    checkYourAnswer: "This is the allowed case. Keep it small so the denied case is easier to compare against."
  },
  {
    starterCode: "const request = { userId: 'u1', resourceOwnerId: 'u2' };\nfunction canReadProfile(req) {\n  return true;\n}\nconsole.log(canReadProfile(request));",
    expectedOutput: "false because the requester does not own the profile.",
    checkYourAnswer: "Broken access control often looks like this: the app checks that someone is logged in but forgets to check ownership."
  },
  {
    starterCode: "const request = { userId: 'u1', role: 'user', requiredRole: 'admin' };\nfunction hasRequiredRole(req) {\n  return true;\n}\nconsole.log(hasRequiredRole(request));",
    expectedOutput: "false because a normal user does not satisfy an admin-only operation.",
    checkYourAnswer: "Ownership and role checks are separate questions. Say which one your code is answering."
  }
];

const securityInjectionOutputPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const comment = '<script>alert(1)</script>';\nfunction escapeHtml(value) {\n  return value;\n}\nconsole.log(escapeHtml(comment));",
    expectedOutput: "The script tags are escaped, not rendered as HTML.",
    checkYourAnswer: "Safe output does not trust stored text just because it already reached your database."
  },
  {
    starterCode: "const name = 'Ada & Grace';\nfunction escapeHtml(value) {\n  return value;\n}\nconsole.log(escapeHtml(name));",
    expectedOutput: "Ada &amp; Grace or an equivalent escaped ampersand.",
    checkYourAnswer: "A safe encoder must preserve normal text while escaping special characters. Do not only test attack-looking input."
  },
  {
    starterCode: "const query = \"python'; DROP TABLE lessons; --\";\nfunction usesParameterizedQuery(sql) {\n  return false;\n}\nconsole.log(usesParameterizedQuery(query));",
    expectedOutput: "The unsafe text is treated as a value, not joined into a SQL command.",
    checkYourAnswer: "This rep is about boundary discipline: values stay values; commands stay commands."
  }
];

export const secureSoftwareLessons: Lesson[] = [
    proofLesson({
      id: "lesson-security-threat-model",
      moduleId: "module-secure-software-core",
      slug: "security-threat-model",
      title: "Threat Notes Before Fix Lists",
      summary: "Name the asset, actor, abuse case, control, and verifier for a small feature.",
      bodyMarkdown: "Secure software starts by naming what could go wrong. A threat note keeps security work tied to a concrete feature and verifier.",
      estimatedMinutes: 11,
      difficulty: "foundation",
      skillIds: ["skill-threat-modeling"],
      quizId: "quiz-security-threat-model",
      desktopTask: "Create a threat note for a profile form or API endpoint.",
      evidencePrompt: "Capture the threat note and the verifier you would run after the control is implemented.",
      language: "Application security",
      tools: ["threat note", "feature boundary", "verifier plan"],
      synopsis: "You are learning to describe security risk in a beginner-friendly way before jumping to tools, scanners, or vague fix lists.",
      prerequisites: ["Know what feature you are reviewing.", "Know that a control is a design or code choice that reduces a risk."],
      testingFocus: "The check confirms that the threat note names an asset, actor, abuse case, control, and verifier.",
      objective: "Write a threat note that maps one feature risk to one testable control.",
      whyItMatters: "Security work becomes practical when risk is tied to a concrete feature and a verifier.",
      coreConcept: "A threat note connects asset, actor, abuse case, control, and verification.",
      workedExample: "For a profile form, the asset is user email, the actor is an unauthenticated visitor, and the control is server-side ownership check.",
      guidedExercise: "Choose one feature, fill the five fields, and reject notes that only say make it secure.",
      missionConnection: "This opens the Secure Review Pack mission.",
      reflectionPrompt: "Which assumption in your threat note would need confirmation from the product owner?",
      practiceStarter: "const threat = { asset: 'user email', actor: 'unauthenticated visitor', abuseCase: 'read another account', control: 'ownership check', verifier: 'access denied test' };",
      practiceExpected: "The threat note has five concrete fields and the verifier prints passed.",
      practiceCheck: "A control without a verifier is only a wish; name how it will be checked.",
      miniTitle: "Draft a five-field threat note",
      miniGoal: "Create one threat note for a small feature and make every field concrete.",
      miniSteps: ["Pick one feature", "Name the protected asset", "Name the actor and abuse case", "Name the control and verifier"],
      miniDeliverables: ["Threat note", "Verifier plan", "Residual assumption"],
      verifierCommand: "Run the Code Lab check or inspect the five-field threat note.",
      expectedEvidence: "A complete threat note with asset, actor, abuse case, control, verifier, and one remaining assumption.",
      projectConnection: "This becomes the risk table in the Secure Review Pack.",
      requiredCodeIncludes: ["asset", "actor", "control", "verifier"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function buildThreatNote(feature) {\n  return { asset: '', actor: '', abuseCase: '', control: '', verifier: '' };\n}\n\nconst note = buildThreatNote('profile');",
      runnerTestCode: "const required = ['asset', 'actor', 'abuseCase', 'control', 'verifier'];\nif (!required.every((key) => typeof note[key] === 'string' && note[key].trim().length > 3)) throw new Error('threat note needs concrete fields');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-security-secrets-auth",
      moduleId: "module-secure-software-core",
      slug: "security-secrets-auth",
      title: "Secrets and Auth Boundaries",
      summary: "Separate public config from secrets and name where auth must be enforced.",
      bodyMarkdown: "A secret is not just any setting. Secure apps keep private credentials out of clients and enforce authorization at server boundaries.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-secret-handling", "skill-auth-boundaries"],
      quizId: "quiz-security-secrets-auth",
      desktopTask: "Classify sample settings as public or secret and name one server-side auth boundary.",
      evidencePrompt: "Capture the classification table and one auth-boundary verifier.",
      language: "Application security",
      tools: ["config table", "auth boundary", "server check"],
      synopsis: "You are learning how to avoid two common beginner mistakes: exposing private keys and trusting client-side checks as authorization.",
      prerequisites: ["Know that frontend code can be inspected by users.", "Know that server code can enforce access before returning data."],
      testingFocus: "The check confirms that secret-looking names are classified as secret and public browser config remains public.",
      objective: "Classify settings and name the server boundary that protects private data.",
      whyItMatters: "Modern apps often fail through leaked keys or authorization checks placed in the wrong layer.",
      coreConcept: "Secrets stay server-side; authorization decisions must be enforced where data is returned or mutated.",
      workedExample: "PUBLIC_API_BASE can be public, but STRIPE_SECRET_KEY and DATABASE_URL are secrets.",
      guidedExercise: "Sort five settings into public or secret, then write one sentence naming the auth boundary.",
      missionConnection: "This supplies the secrets and auth section of the Secure Review Pack.",
      reflectionPrompt: "Which value would be most damaging if copied into a mobile bundle?",
      practiceStarter: "const settings = ['PUBLIC_API_BASE', 'DATABASE_URL', 'STRIPE_SECRET_KEY'];",
      practiceExpected: "Secret-like settings are marked secret, public base URLs are marked public, and the verifier prints passed.",
      practiceCheck: "If the browser or mobile bundle needs it to render, it might be public; if it grants power, it is secret.",
      practiceReps: securitySecretPracticeReps,
      miniTitle: "Classify config and auth boundaries",
      miniGoal: "Create a small config table and one server-side authorization note.",
      miniSteps: ["List public settings", "List secret settings", "Name the protected operation", "Name the server-side verifier"],
      miniDeliverables: ["Config table", "Auth-boundary note", "Check output"],
      verifierCommand: "Run the Code Lab check or inspect the classification table.",
      expectedEvidence: "A config classification table, auth-boundary note, and check output proving secrets are not treated as public.",
      projectConnection: "This becomes the config hygiene section of the Secure Review Pack.",
      requiredCodeIncludes: ["classifySetting", "secret"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function classifySetting(name) {\n  return 'public';\n}",
      runnerTestCode: "if (classifySetting('STRIPE_SECRET_KEY') !== 'secret') throw new Error('secret keys must be secret');\nif (classifySetting('DATABASE_URL') !== 'secret') throw new Error('database urls must be secret');\nif (classifySetting('PUBLIC_API_BASE') !== 'public') throw new Error('public api base can be public');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-security-access-control-lab",
      moduleId: "module-secure-software-core",
      slug: "security-access-control-lab",
      title: "Broken Access Control: Exploit, Fix, Verify",
      summary: "Prove that a user can only access resources they own or are allowed to manage.",
      bodyMarkdown: "Access control is the rule that decides who may read or change a resource. Beginners often check only that a user is logged in, then forget to check ownership or role. This lesson stages the secure habit: show the broken case, write the smallest rule, and verify both allowed and denied access.",
      estimatedMinutes: 12,
      difficulty: "applied",
      skillIds: ["skill-auth-boundaries", "skill-threat-modeling", "skill-testing-debugging"],
      quizId: "quiz-security-access-control-lab",
      desktopTask: "Write an ownership check for a profile read action and test both the owner and non-owner case.",
      evidencePrompt: "Capture the broken case, fixed rule, denied request, allowed request, and check output.",
      language: "Application security",
      tools: ["access rule", "negative test", "ownership check"],
      synopsis: "You are learning the difference between authentication and authorization with one tiny resource rule.",
      prerequisites: ["Know that logged-in means identity is known.", "Know that authorization decides what that identity may access."],
      testingFocus: "The check confirms owner access is allowed and non-owner access is denied.",
      objective: "Write an ownership rule that allows the owner and rejects a different user.",
      whyItMatters: "Broken access control is common because happy-path testing often proves login but skips ownership.",
      coreConcept: "Authentication asks who the user is; authorization asks whether that user may access this specific resource.",
      workedExample: "User u1 may read profile owned by u1, but user u1 must not read a profile owned by u2.",
      guidedExercise: "Implement canReadProfile, test the owner case, then test the non-owner case before calling the rule done.",
      missionConnection: "This deepens the auth-boundary part of the Secure Review Pack.",
      reflectionPrompt: "Which denied request would catch the bug if someone only tested logged-in users?",
      practiceStarter: "function canReadProfile(request) {\n  return true;\n}\n\nconsole.log(canReadProfile({ userId: 'u1', resourceOwnerId: 'u2' }));",
      practiceExpected: "Owner requests pass, non-owner requests fail, and the check prints passed.",
      practiceCheck: "If every logged-in user passes, you tested authentication but not authorization.",
      practiceReps: securityAccessControlPracticeReps,
      miniTitle: "Verify profile ownership",
      miniGoal: "Create one access-control rule with an allowed owner case and denied non-owner case.",
      miniSteps: ["Name the protected resource", "Write the owner rule", "Test owner access", "Test non-owner denial"],
      miniDeliverables: ["Access rule", "Allowed test", "Denied test", "Short broken-case note"],
      verifierCommand: "Run the Code Lab check or local access-control test.",
      expectedEvidence: "Access-rule code and output showing owner access allowed, non-owner access denied, and the broken case explained.",
      projectConnection: "This becomes the access-control lab inside the Secure Review Pack.",
      requiredCodeIncludes: ["canReadProfile", "userId", "resourceOwnerId"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function canReadProfile(request) {\n  return true;\n}",
      runnerTestCode: "if (!canReadProfile({ userId: 'u1', resourceOwnerId: 'u1' })) throw new Error('owner should be allowed');\nif (canReadProfile({ userId: 'u1', resourceOwnerId: 'u2' })) throw new Error('non-owner should be denied');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-security-input-validation",
      moduleId: "module-secure-software-core",
      slug: "security-input-validation",
      title: "Validate Inputs at the Boundary",
      summary: "Reject malformed input with clear errors before domain logic trusts it.",
      bodyMarkdown: "Input validation protects the boundary between untrusted data and trusted application logic. Good validation rejects bad data without leaking internals.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-auth-boundaries", "skill-testing-debugging"],
      quizId: "quiz-security-input-validation",
      desktopTask: "Write a validator for one small profile payload with a negative test.",
      evidencePrompt: "Capture the valid case, rejected case, and safe error text.",
      language: "Application security",
      tools: ["validator", "negative test", "safe error"],
      synopsis: "You are learning to treat outside input as untrusted until it passes a small, explicit validation boundary.",
      prerequisites: ["Know that form and API data can be malformed.", "Know that error messages should help without exposing internals."],
      testingFocus: "The check confirms that valid input passes and malformed email or role input fails with a safe message.",
      objective: "Write a boundary validator with one valid case and one rejected case.",
      whyItMatters: "Boundary validation prevents messy or hostile input from spreading through the app.",
      coreConcept: "Validate shape and allowed values before domain logic uses input.",
      workedExample: "A role field should accept learner or mentor, not any arbitrary string.",
      guidedExercise: "Validate email and role fields, then return safe errors for invalid values.",
      missionConnection: "This adds the input-validation proof to the Secure Review Pack.",
      reflectionPrompt: "What internal detail should your error message avoid revealing?",
      practiceStarter: "const input = { email: 'learner@example.com', role: 'learner' };",
      practiceExpected: "Valid input passes, bad email or role fails, and the verifier prints passed.",
      practiceCheck: "Do not let unknown role values through just because the email looks valid.",
      miniTitle: "Build a boundary validator",
      miniGoal: "Create a validator that accepts one safe payload and rejects two unsafe payloads.",
      miniSteps: ["Define allowed fields", "Accept the valid payload", "Reject malformed email", "Reject unsupported role"],
      miniDeliverables: ["Validator code", "Valid-case output", "Rejected-case output"],
      verifierCommand: "Run the Code Lab check or local validation tests.",
      expectedEvidence: "Validator code, valid and rejected case output, safe error text, and passing check output.",
      projectConnection: "This is the validation evidence in the Secure Review Pack.",
      requiredCodeIncludes: ["validateProfile", "errors"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function validateProfile(input) {\n  return { ok: true, errors: [] };\n}",
      runnerTestCode: "if (!validateProfile({ email: 'learner@example.com', role: 'learner' }).ok) throw new Error('valid input should pass');\nif (validateProfile({ email: 'bad', role: 'learner' }).ok) throw new Error('bad email should fail');\nif (validateProfile({ email: 'learner@example.com', role: 'admin' }).ok) throw new Error('unsupported role should fail');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-security-injection-output-encoding",
      moduleId: "module-secure-software-core",
      slug: "security-injection-output-encoding",
      title: "Injection Boundaries and Safe Output",
      summary: "Keep user text as data and escape it before display.",
      bodyMarkdown: "Injection bugs happen when untrusted text crosses a boundary and starts acting like a command or markup. A beginner does not need every attack family at once. Start with one habit: keep values separate from commands, then encode user-controlled text before it appears in HTML, logs, or query strings.",
      estimatedMinutes: 12,
      difficulty: "applied",
      skillIds: ["skill-auth-boundaries", "skill-testing-debugging"],
      quizId: "quiz-security-injection-output-encoding",
      desktopTask: "Write a tiny HTML escape function and test normal text plus script-looking text.",
      evidencePrompt: "Capture the unsafe input, escaped output, normal-text case, and check output.",
      language: "Application security",
      tools: ["output encoding", "negative test", "safe text"],
      synopsis: "You are learning one concrete injection defense: user text remains text and must not become executable markup.",
      prerequisites: ["Know that users can type unexpected characters.", "Know that HTML treats angle brackets specially."],
      testingFocus: "The check confirms script-looking text is escaped while normal text remains readable.",
      objective: "Escape untrusted text before displaying it as HTML-like output.",
      whyItMatters: "Safe output prevents a stored note, comment, or name field from becoming active markup.",
      coreConcept: "Boundary safety keeps commands and markup separate from user-controlled values.",
      workedExample: "<script>alert(1)</script> should display as escaped text, not run as a script.",
      guidedExercise: "Write escapeHtml, test a script-looking string, then test a normal name with an ampersand.",
      missionConnection: "This adds injection-boundary thinking to the Secure Review Pack.",
      reflectionPrompt: "Which output location would need escaping before a reviewer could trust it?",
      practiceStarter: "function escapeHtml(value) {\n  return value;\n}\n\nconsole.log(escapeHtml('<script>alert(1)</script>'));",
      practiceExpected: "Special HTML characters are escaped, normal text stays readable, and the check prints passed.",
      practiceCheck: "If the output still contains raw <script>, the text can still be interpreted as markup.",
      practiceReps: securityInjectionOutputPracticeReps,
      miniTitle: "Escape user-controlled output",
      miniGoal: "Create one output-encoding helper with safe and normal examples.",
      miniSteps: ["Choose the unsafe input", "Escape special HTML characters", "Test a normal text case", "Explain the boundary"],
      miniDeliverables: ["escapeHtml helper", "Unsafe-input output", "Normal-input output", "Boundary note"],
      verifierCommand: "Run the Code Lab check or local output-encoding test.",
      expectedEvidence: "Encoding helper and output showing script-looking text escaped, normal text preserved, and check output passing.",
      projectConnection: "This becomes the injection-boundary section of the Secure Review Pack.",
      requiredCodeIncludes: ["escapeHtml", "replace"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function escapeHtml(value) {\n  return value;\n}",
      runnerTestCode: "const escaped = escapeHtml('<script>alert(1)</script>');\nif (escaped.includes('<script>')) throw new Error('script tag should be escaped');\nif (!escaped.includes('&lt;script&gt;')) throw new Error('escaped output should show encoded tag');\nif (!escapeHtml('Ada & Grace').includes('&amp;')) throw new Error('ampersand should be escaped');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-security-dependency-logging",
      moduleId: "module-secure-software-core",
      slug: "security-dependency-logging",
      title: "Dependencies and Logs Need Guardrails",
      summary: "Review dependency risk and logging behavior without leaking private data.",
      bodyMarkdown: "Security proof includes the boring parts: dependency review, version notes, safe logs, and clear residual risk.",
      estimatedMinutes: 10,
      difficulty: "applied",
      skillIds: ["skill-dependency-hygiene", "skill-secret-handling"],
      quizId: "quiz-security-dependency-logging",
      desktopTask: "Create a release-risk note with dependency and logging checks.",
      evidencePrompt: "Capture the dependency note, log redaction note, and check output.",
      language: "Application security",
      tools: ["dependency note", "safe logs", "release checklist"],
      synopsis: "You are learning the practical AppSec habit of checking package risk and log safety before claiming a release is ready.",
      prerequisites: ["Know that dependencies can change app behavior.", "Know that logs can accidentally reveal sensitive values."],
      testingFocus: "The check confirms that a release review flags unpinned dependencies and raw secret logging.",
      objective: "Create a dependency and logging checklist for one small release.",
      whyItMatters: "Real incidents often come from package drift or logs that expose private data.",
      coreConcept: "Release hygiene checks dependency freshness, pinning, vulnerability notes, and safe log redaction.",
      workedExample: "A review should flag unpinned helper packages and any log line that prints token values.",
      guidedExercise: "Review a sample release object and return every risk that needs a fix.",
      missionConnection: "This completes the Secure Review Pack before portfolio evidence.",
      reflectionPrompt: "Which risk would block release and which could become a follow-up ticket?",
      practiceStarter: "const release = { pinned: false, logsSecrets: true, verifier: 'npm test passed' };",
      practiceExpected: "The review flags dependency pinning and secret logging, then the verifier prints passed.",
      practiceCheck: "A passing test suite does not prove logs are safe or dependencies are pinned.",
      miniTitle: "Review dependency and log hygiene",
      miniGoal: "Create a release checklist that flags package and logging risks.",
      miniSteps: ["Check dependency pinning", "Check vulnerability or update notes", "Check whether logs expose secrets", "Record release decision"],
      miniDeliverables: ["Release-risk note", "Safe-log note", "Check output"],
      verifierCommand: "Run the Code Lab check or inspect the release checklist.",
      expectedEvidence: "Release checklist, dependency note, safe-log note, release decision, and passing check output.",
      projectConnection: "This closes the Secure Review Pack with release hygiene evidence.",
      requiredCodeIncludes: ["reviewRelease", "risks"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function reviewRelease(release) {\n  return [];\n}",
      runnerTestCode: "const risks = reviewRelease({ pinned: false, logsSecrets: true, verifier: 'npm test passed' });\nif (!risks.includes('pin dependencies')) throw new Error('must flag unpinned dependencies');\nif (!risks.includes('redact secret logs')) throw new Error('must flag secret logging');\nif (reviewRelease({ pinned: true, logsSecrets: false, verifier: 'npm test passed' }).length !== 0) throw new Error('clean release should have no risks');\nconsole.log('passed');"
    }),
];

export const secureSoftwareQuizzes: Quiz[] = [
  checkpointQuiz("quiz-security-threat-model", "lesson-security-threat-model", "Threat note checkpoint", "a threat note", "Connecting an asset, actor, abuse case, control, and verifier", "Listing random tools before naming the risk", "Marking every feature as equally risky", "Threat notes make security work concrete enough to test."),
  checkpointQuiz("quiz-security-secrets-auth", "lesson-security-secrets-auth", "Secrets and auth checkpoint", "secret and auth boundaries", "Keeping secrets server-side and enforcing authorization at data boundaries", "Putting every setting in public client code", "Trusting a hidden button as authorization", "Secrets and authorization decisions need the correct boundary."),
  checkpointQuiz("quiz-security-access-control-lab", "lesson-security-access-control-lab", "Access control checkpoint", "broken access control", "Proving both allowed owner access and denied non-owner access", "Treating logged-in as allowed for every record", "Testing only the happy path owner case", "Authorization must compare the requester to the specific resource or action."),
  checkpointQuiz("quiz-security-input-validation", "lesson-security-input-validation", "Input validation checkpoint", "boundary input validation", "Rejecting malformed or unsupported input before domain logic trusts it", "Passing every payload through if one field looks right", "Returning internal stack traces as user-facing errors", "Validation protects domain logic from untrusted input."),
  checkpointQuiz("quiz-security-injection-output-encoding", "lesson-security-injection-output-encoding", "Output encoding checkpoint", "safe output encoding", "Escaping user-controlled text before rendering it as markup", "Deleting all user text to avoid escaping", "Letting raw script-looking text survive in output", "Output encoding preserves text while keeping commands and markup separate."),
  checkpointQuiz("quiz-security-dependency-logging", "lesson-security-dependency-logging", "Dependency and logging checkpoint", "dependency and log hygiene", "Flagging package drift and preventing logs from exposing private data", "Treating passing tests as proof that logs are safe", "Printing tokens so debugging is easier", "Release hygiene includes dependencies and safe logs, not only functional tests."),
];
