import type { Lesson, LessonPracticeBlock, Quiz } from "@/domain/types";
import { checkpointQuiz, proofLesson } from "../python/shared";

// Data Systems track. Mirrors the python/level-N.ts split: this file owns the
// track's lessons and quizzes, and the shared builders in
// src/content/python/shared.ts do the rest.

const dataContractsPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const row = { userId: 'u1', minutes: 30, topic: 'python' };\nfunction isLearningRow(row) {\n  return false;\n}\nconsole.log(isLearningRow(row));",
    expectedOutput: "true because the row has userId, numeric minutes, and topic.",
    checkYourAnswer: "A dataset contract names the fields a report can trust before any aggregation starts."
  },
  {
    starterCode: "const row = { userId: 'u1', minutes: -5, topic: 'python' };\nfunction isLearningRow(row) {\n  return true;\n}\nconsole.log(isLearningRow(row));",
    expectedOutput: "false because minutes cannot be negative.",
    checkYourAnswer: "A fixture should include a bad row on purpose. That proves the contract rejects impossible data."
  },
  {
    starterCode: "const fixture = [{ userId: 'u1', minutes: 30, topic: 'python' }];\nconsole.log(fixture.length);",
    expectedOutput: "1 sample row available for repeatable tests.",
    checkYourAnswer: "Fixtures make tests repeatable. If the only sample is a live export, a reviewer cannot easily reproduce the result."
  }
];

const dataRejectedRowPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const row = { rowNumber: 2, minutes: '', topic: 'python' };\nfunction rejectionReason(row) {\n  return '';\n}\nconsole.log(rejectionReason(row));",
    expectedOutput: "missing minutes is reported as the rejection reason.",
    checkYourAnswer: "A rejected row needs a reason that tells the data owner what to fix."
  },
  {
    starterCode: "const rejected = [{ rowNumber: 3, raw: 'git,-5', reason: 'negative minutes' }];\nconsole.log(rejected[0].reason);",
    expectedOutput: "negative minutes is reported as the rejection reason.",
    checkYourAnswer: "Keep row number, raw value, and reason together. Without the raw value, debugging becomes guesswork."
  },
  {
    starterCode: "const report = { accepted: 8, rejected: 2, reasons: ['missing topic', 'negative minutes'] };\nconsole.log(report.accepted + report.rejected);",
    expectedOutput: "10 total input rows accounted for.",
    checkYourAnswer: "A quality report should account for accepted plus rejected rows so bad data does not disappear silently."
  }
];

export const dataSystemsLessons: Lesson[] = [
    proofLesson({
      id: "lesson-data-quality-rules",
      moduleId: "module-data-systems-core",
      slug: "data-quality-rules",
      title: "Data Quality Rules Before Reports",
      summary: "Define accepted and rejected rows before building a product-facing report.",
      bodyMarkdown: "Data systems work starts with deciding what records are trustworthy enough to use. Quality rules make those decisions visible.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-data-quality", "skill-sql-joins"],
      quizId: "quiz-data-quality-rules",
      desktopTask: "Write three data quality rules for a small learning-events dataset.",
      evidencePrompt: "Capture accepted rows, rejected rows, reasons, and check output.",
      language: "Data systems",
      tools: ["quality rules", "rejected rows", "SQL-shaped records"],
      synopsis: "You are learning to protect product decisions from bad records by naming quality rules before creating reports or dashboards.",
      prerequisites: ["Know that datasets are made of rows.", "Know that bad rows should be rejected with reasons."],
      testingFocus: "The check confirms that missing user ids and negative minutes are rejected with reasons.",
      objective: "Create data quality rules that separate accepted and rejected records.",
      whyItMatters: "Reports built on unchecked data can mislead teams even when the query runs successfully.",
      coreConcept: "Data quality rules define which rows are valid and why rejected rows are excluded.",
      workedExample: "A learning event needs a user id, a positive minute count, and a known event type.",
      guidedExercise: "Validate three sample rows and return accepted count, rejected count, and reasons.",
      missionConnection: "This starts the Data Quality Report mission.",
      reflectionPrompt: "Which rejected row would most distort a progress report if it slipped through?",
      practiceStarter: "const rows = [{ userId: 'u1', minutes: 20 }, { userId: '', minutes: -5 }];",
      practiceExpected: "One row is accepted, one row is rejected with a reason, and the verifier prints passed.",
      practiceCheck: "A rejected row without a reason is hard to fix upstream.",
      miniTitle: "Create quality rules for event rows",
      miniGoal: "Validate sample rows and record accepted/rejected counts with reasons.",
      miniSteps: ["Name required fields", "Reject missing user ids", "Reject negative minutes", "Record rejected-row reasons"],
      miniDeliverables: ["Quality rules", "Accepted/rejected counts", "Rejected-row reasons"],
      verifierCommand: "Run the Code Lab check or local data-quality test.",
      expectedEvidence: "Quality-rule artifact, accepted/rejected row output, rejected reasons, and passing check output.",
      projectConnection: "This is the input gate for the Data Quality Report.",
      requiredCodeIncludes: ["validateRows", "rejected"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function validateRows(rows) {\n  return { accepted: rows.length, rejected: 0, reasons: [] };\n}",
      runnerTestCode: "const result = validateRows([{ userId: 'u1', minutes: 20 }, { userId: '', minutes: 10 }, { userId: 'u2', minutes: -1 }]);\nif (result.accepted !== 1 || result.rejected !== 2) throw new Error('should accept one row and reject two');\nif (result.reasons.length !== 2) throw new Error('each rejected row needs a reason');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-data-contracts-fixtures",
      moduleId: "module-data-systems-core",
      slug: "data-contracts-fixtures",
      title: "Dataset Contracts and Test Fixtures",
      summary: "Define the row shape and tiny sample data before writing report logic.",
      bodyMarkdown: "A dataset contract is a small promise about each row: which fields must exist, which types are allowed, and which examples prove the rule. Test fixtures are tiny sample rows you keep stable so the same contract can be checked tomorrow. Start with one valid row and one obvious bad row before building any report.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-data-quality", "skill-testing-debugging"],
      quizId: "quiz-data-contracts-fixtures",
      desktopTask: "Create a row contract and two fixtures for learning-event data.",
      evidencePrompt: "Capture the required fields, one valid fixture, one rejected fixture, and check output.",
      language: "Data systems",
      tools: ["dataset contract", "fixtures", "row validator"],
      synopsis: "You are learning to freeze a tiny row shape before report logic depends on it.",
      prerequisites: ["Know that datasets are made of rows.", "Know that tests can use small sample inputs."],
      testingFocus: "The check confirms fixtures include required fields and reject the wrong type for minutes.",
      objective: "Build a tiny dataset contract with repeatable fixture rows.",
      whyItMatters: "Reports are easier to trust when their input shape is checked before totals are calculated.",
      coreConcept: "A dataset contract names required fields, and fixtures prove the contract with stable examples.",
      workedExample: "A learning event row needs userId, numeric minutes, and topic; a fixture with text minutes should fail.",
      guidedExercise: "Validate two fixture rows and summarize which fields the contract requires.",
      missionConnection: "This prepares the input contract for the Data Quality Report mission.",
      reflectionPrompt: "Which field would break the report fastest if its type changed?",
      practiceStarter: "const fixtures = [{ userId: 'u1', minutes: 30, topic: 'python' }, { userId: 'u2', minutes: '30', topic: 'git' }];",
      practiceExpected: "One fixture passes, one fixture fails, required fields are listed, and the check prints passed.",
      practiceCheck: "Do not let a fixture pass just because it has similar-looking values.",
      practiceReps: dataContractsPracticeReps,
      miniTitle: "Create a dataset contract",
      miniGoal: "Define required learning-event fields and prove them with tiny fixtures.",
      miniSteps: ["Name required fields", "Create one valid fixture", "Create one bad fixture", "Run the contract check"],
      miniDeliverables: ["Dataset contract", "Valid fixture", "Rejected fixture", "Check output"],
      verifierCommand: "Run the Code Lab check or local fixture-contract test.",
      expectedEvidence: "Contract fields, valid fixture, rejected fixture, reason for rejection, and passing check output.",
      projectConnection: "This is the contract proof for the Data Quality Report.",
      requiredCodeIncludes: ["validateLearningRow", "fixtures"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "const fixtures = [\n  { userId: 'u1', minutes: 30, topic: 'python' },\n  { userId: 'u2', minutes: '30', topic: 'git' }\n];\n\nfunction validateLearningRow(row) {\n  return true;\n}\n\nfunction contractSummary(rows) {\n  return { fields: [], valid: rows.length, invalid: 0 };\n}",
      runnerTestCode: "const result = contractSummary(fixtures);\nif (!Array.isArray(result.fields) || !['userId', 'minutes', 'topic'].every((field) => result.fields.includes(field))) throw new Error('contract must list required fields');\nif (result.valid !== 1 || result.invalid !== 1) throw new Error('fixtures should include one valid and one invalid row');\nif (validateLearningRow({ userId: 'u3', minutes: '25', topic: 'sql' })) throw new Error('text minutes should fail');\nif (!validateLearningRow({ userId: 'u4', minutes: 25, topic: 'sql' })) throw new Error('valid row should pass');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-data-rejected-row-proof",
      moduleId: "module-data-systems-core",
      slug: "data-rejected-row-proof",
      title: "Rejected Rows Need Reasons",
      summary: "Record why each bad row was rejected so data problems stay fixable.",
      bodyMarkdown: "A rejected row should not vanish into a quiet counter. The reason explains what failed and gives the next person a fixable clue, such as missing userId or negative minutes. Keep the row number, raw value, and reason together so a reviewer can confirm every input row was either accepted or rejected deliberately.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-data-quality", "skill-portfolio-evidence"],
      quizId: "quiz-data-rejected-row-proof",
      desktopTask: "Build a rejected-row report with row number, raw value, and reason.",
      evidencePrompt: "Capture accepted count, rejected rows with reasons, total accounted rows, and check output.",
      language: "Data systems",
      tools: ["rejected-row report", "reason codes", "input accounting"],
      synopsis: "You are learning to make bad data explain itself instead of disappearing from a report.",
      prerequisites: ["Know that invalid rows should not be used in totals.", "Know that a rejected row still needs to be reviewed."],
      testingFocus: "The check confirms each rejected row keeps row number, raw value, and a specific reason.",
      objective: "Create rejected-row proof that explains every dropped input.",
      whyItMatters: "Silent drops make reports look clean while hiding data problems someone needs to fix.",
      coreConcept: "A rejected-row proof preserves enough context to debug the original input and confirm no row disappeared.",
      workedExample: "A row with blank userId should be rejected with rowNumber, raw value, and reason: missing userId.",
      guidedExercise: "Review three rows, accept one, reject two, and attach a reason to each rejected row.",
      missionConnection: "This strengthens the rejected-row section of the Data Quality Report mission.",
      reflectionPrompt: "Which rejection reason would be easiest for a data owner to fix?",
      practiceStarter: "const rows = [{ rowNumber: 1, userId: 'u1', minutes: 20, raw: 'u1,20,python' }, { rowNumber: 2, userId: '', minutes: 15, raw: ',15,git' }];",
      practiceExpected: "One row is accepted, one row is rejected with rowNumber, raw value, reason, and the check prints passed.",
      practiceCheck: "Do not return only a rejected count; keep the reason attached to the row.",
      practiceReps: dataRejectedRowPracticeReps,
      miniTitle: "Create rejected-row proof",
      miniGoal: "Account for every input row with either accepted output or a reviewable rejection reason.",
      miniSteps: ["Validate each row", "Accept clean rows", "Reject bad rows with reasons", "Confirm accepted plus rejected equals input count"],
      miniDeliverables: ["Accepted rows", "Rejected-row list", "Reason summary", "Check output"],
      verifierCommand: "Run the Code Lab check or local rejected-row test.",
      expectedEvidence: "Accepted count, rejected rows with rowNumber/raw/reason, total input accounting, and passing check output.",
      projectConnection: "This is the rejected-row proof for the Data Quality Report.",
      requiredCodeIncludes: ["reviewRows", "reason"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "const rows = [\n  { rowNumber: 1, userId: 'u1', minutes: 20, raw: 'u1,20,python' },\n  { rowNumber: 2, userId: '', minutes: 15, raw: ',15,git' },\n  { rowNumber: 3, userId: 'u3', minutes: -5, raw: 'u3,-5,sql' }\n];\n\nfunction reviewRows(rows) {\n  return { accepted: rows, rejected: [] };\n}",
      runnerTestCode: "const result = reviewRows(rows);\nif (result.accepted.length !== 1) throw new Error('only one row should be accepted');\nif (result.rejected.length !== 2) throw new Error('two rows should be rejected');\nif (result.accepted.length + result.rejected.length !== rows.length) throw new Error('every input row must be accounted for');\nfor (const rejected of result.rejected) {\n  if (typeof rejected.rowNumber !== 'number') throw new Error('rejected row needs rowNumber');\n  if (typeof rejected.raw !== 'string' || rejected.raw.length === 0) throw new Error('rejected row needs raw value');\n  if (typeof rejected.reason !== 'string' || rejected.reason.length < 4) throw new Error('rejected row needs reason');\n}\nif (!result.rejected.some((row) => row.reason.includes('user'))) throw new Error('missing user reason required');\nif (!result.rejected.some((row) => row.reason.includes('minutes'))) throw new Error('minutes reason required');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-data-pipeline-lineage",
      moduleId: "module-data-systems-core",
      slug: "data-pipeline-lineage",
      title: "Pipeline Lineage Shows Where Data Came From",
      summary: "Map source, transform, output, owner, and verifier for a small data flow.",
      bodyMarkdown: "Lineage prevents mystery data. A simple pipeline note shows where records come from, how they change, and what verifies each stage.",
      estimatedMinutes: 10,
      difficulty: "applied",
      skillIds: ["skill-data-pipelines"],
      quizId: "quiz-data-pipeline-lineage",
      desktopTask: "Create a three-stage lineage note for raw events to weekly summary.",
      evidencePrompt: "Capture source, transform, output, owner, verifier, and one risk.",
      language: "Data systems",
      tools: ["lineage map", "pipeline stages", "verifier note"],
      synopsis: "You are learning how to make a data flow inspectable so a reviewer can trace a number back to its source and transformation.",
      prerequisites: ["Know that raw records can be transformed.", "Know that a report should cite its data source."],
      testingFocus: "The check confirms that source, transform, output, owner, and verifier exist for every stage.",
      objective: "Build a lineage map for a small data pipeline.",
      whyItMatters: "Data work is more credible when every output can be traced and verified.",
      coreConcept: "Lineage records source, transform, output, owner, and verification for each stage.",
      workedExample: "Raw events become cleaned events, then weekly totals, with checks at each boundary.",
      guidedExercise: "Create three stages and make sure every stage has the five required fields.",
      missionConnection: "This adds lineage proof to the Data Quality Report.",
      reflectionPrompt: "Which stage would be hardest to debug without lineage?",
      practiceStarter: "const stages = [{ source: 'raw events', transform: 'clean rows', output: 'clean events' }];",
      practiceExpected: "Every stage has source, transform, output, owner, verifier, and the verifier prints passed.",
      practiceCheck: "If a stage lacks an owner or verifier, the pipeline is hard to operate.",
      miniTitle: "Map a three-stage data pipeline",
      miniGoal: "Create lineage for raw input, cleaned records, and final report output.",
      miniSteps: ["Name the raw source", "Name the cleaning transform", "Name the report output", "Attach owner and verifier to each stage"],
      miniDeliverables: ["Lineage map", "Stage verifier notes", "Pipeline risk note"],
      verifierCommand: "Run the Code Lab check or inspect the lineage map.",
      expectedEvidence: "Lineage map with source, transform, output, owner, verifier, risk note, and passing check output.",
      projectConnection: "This is the lineage section of the Data Quality Report.",
      requiredCodeIncludes: ["buildLineage", "verifier"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function buildLineage() {\n  return [];\n}\n\nconst stages = buildLineage();",
      runnerTestCode: "const required = ['source', 'transform', 'output', 'owner', 'verifier'];\nif (stages.length < 3) throw new Error('lineage needs at least three stages');\nif (!stages.every((stage) => required.every((key) => typeof stage[key] === 'string' && stage[key].length > 2))) throw new Error('every stage needs required fields');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-data-reproducible-report",
      moduleId: "module-data-systems-core",
      slug: "data-reproducible-report",
      title: "Reproducible Reports Beat One-Off Screenshots",
      summary: "Record query, input version, output, verifier, and limitations for a small report.",
      bodyMarkdown: "A report is stronger when another person can rerun it. Reproducible reports include query logic, input version, output, and limits.",
      estimatedMinutes: 10,
      difficulty: "applied",
      skillIds: ["skill-reproducible-report", "skill-data-quality"],
      quizId: "quiz-data-reproducible-report",
      desktopTask: "Create a reproducible report note for weekly learning totals.",
      evidencePrompt: "Capture query logic, input version, output rows, verifier, and limitations.",
      language: "Data systems",
      tools: ["report note", "query logic", "limitations"],
      synopsis: "You are learning how to make a product-facing data report rerunnable instead of relying on a one-time screenshot.",
      prerequisites: ["Know that reports come from inputs and query logic.", "Know that limitations should be stated beside results."],
      testingFocus: "The check confirms that the report includes query, input version, output rows, verifier, and limitations.",
      objective: "Create a reproducible report artifact with explicit limitations.",
      whyItMatters: "Hiring managers and teammates can trust reports that show how they were produced.",
      coreConcept: "Reproducibility means another person can identify inputs, run logic, inspect output, and understand limits.",
      workedExample: "Weekly totals should name the source file, query or transform, generated output, and missing-data limitation.",
      guidedExercise: "Build a report object with the required fields and reject one missing-limitation report.",
      missionConnection: "This completes the Data Quality Report mission.",
      reflectionPrompt: "Which limitation would change the decision someone makes from this report?",
      practiceStarter: "const report = { query: 'sum minutes by week', inputVersion: 'events-v1', rows: 3, limitations: ['toy data'] };",
      practiceExpected: "The report includes query, input version, rows, verifier, limitations, and the verifier prints passed.",
      practiceCheck: "A report without limitations sounds more certain than the data allows.",
      miniTitle: "Write a reproducible report note",
      miniGoal: "Create a report artifact that another person can rerun and critique.",
      miniSteps: ["Name input version", "Name query or transform", "Show output rows", "Attach verifier and limitations"],
      miniDeliverables: ["Report note", "Output rows", "Limitations section"],
      verifierCommand: "Run the Code Lab check or inspect the reproducible report note.",
      expectedEvidence: "Report note with query, input version, output rows, verifier, limitations, and passing check output.",
      projectConnection: "This closes the Data Quality Report with reproducible evidence.",
      requiredCodeIncludes: ["makeReport", "limitations"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function makeReport(input) {\n  return { query: '', inputVersion: '', rows: 0, verifier: '', limitations: [] };\n}",
      runnerTestCode: "const report = makeReport({ version: 'events-v1', rows: [{ minutes: 20 }, { minutes: 30 }] });\nif (!report.query || report.inputVersion !== 'events-v1') throw new Error('report needs query and input version');\nif (report.rows !== 2 || !report.verifier) throw new Error('report needs rows and verifier');\nif (!Array.isArray(report.limitations) || report.limitations.length === 0) throw new Error('report needs limitations');\nconsole.log('passed');"
    })
];

export const dataSystemsQuizzes: Quiz[] = [
  checkpointQuiz("quiz-data-quality-rules", "lesson-data-quality-rules", "Data quality checkpoint", "data quality rules", "Separating accepted rows from rejected rows with reasons", "Building reports before checking input records", "Dropping bad rows without saying why", "Quality rules make report inputs trustworthy and debuggable."),
  checkpointQuiz("quiz-data-contracts-fixtures", "lesson-data-contracts-fixtures", "Dataset contracts checkpoint", "dataset contracts and fixtures", "Naming required row fields and proving them with stable good and bad fixtures", "Building report logic before checking input shape", "Letting text minutes pass as numeric minutes", "Dataset contracts keep report inputs inspectable and repeatable."),
  checkpointQuiz("quiz-data-rejected-row-proof", "lesson-data-rejected-row-proof", "Rejected-row proof checkpoint", "rejected-row proof", "Keeping row number, raw value, and reason for each rejected input", "Returning only a rejected count", "Dropping bad rows silently", "Rejected-row proof makes bad data fixable instead of invisible."),
  checkpointQuiz("quiz-data-pipeline-lineage", "lesson-data-pipeline-lineage", "Pipeline lineage checkpoint", "pipeline lineage", "Tracing source, transform, output, owner, and verifier for each stage", "Treating final numbers as self-explanatory", "Removing owners from the pipeline note", "Lineage makes report outputs traceable."),
  checkpointQuiz("quiz-data-reproducible-report", "lesson-data-reproducible-report", "Reproducible report checkpoint", "a reproducible report", "Naming input version, query logic, output, verifier, and limitations", "Sharing a one-off screenshot with no source", "Omitting limitations to sound more confident", "Reproducible reports can be rerun and critiqued.")
];
