import type { Lesson, Quiz } from "@/domain/types";
import { checkpointQuiz, proofLesson } from "../python/shared";

// Testing and Debugging track. Mirrors the python/level-N.ts split: this file owns the
// track's lessons and quizzes, and the shared builders in
// src/content/python/shared.ts do the rest.

export const testingDebuggingLessons: Lesson[] = [
    proofLesson({
      id: "lesson-testing-regression-harness",
      moduleId: "module-testing-debugging-core",
      slug: "testing-regression-harness",
      title: "Regression Harnesses Catch Repeat Bugs",
      summary: "Turn a fixed bug into a tiny check that fails if the bug returns.",
      bodyMarkdown: "A regression test is a promise that a known bug stays fixed. The smallest useful harness names the input, expected result, and check output.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-testing-debugging", "skill-regression-testing"],
      quizId: "quiz-testing-regression-harness",
      desktopTask: "Write a tiny function plus two cases: one normal case and one case that used to fail.",
      evidencePrompt: "Capture the cases, the check output, and the bug that would return if the check were removed.",
      language: "Testing",
      tools: ["JavaScript", "test cases", "terminal"],
      synopsis: "You are learning how to preserve a bug fix with a tiny repeatable check instead of trusting memory or a manual click path.",
      prerequisites: ["Know that code can be run more than once.", "Know that a test compares actual behavior with expected behavior."],
      testingFocus: "The check confirms that the normal case passes and that invalid input is rejected without pretending the result is valid.",
      objective: "Create a regression harness with one happy path and one old-bug path.",
      whyItMatters: "Employers value beginners who can prevent solved problems from coming back.",
      coreConcept: "A regression harness is a repeatable check for behavior that must not break again.",
      workedExample: "If a minutes parser once accepted empty input, the harness should include an empty-input case that expects invalid.",
      guidedExercise: "Write summarizeMinutes, run two cases, and make the verifier print passed only when both cases behave correctly.",
      missionConnection: "This starts the Regression Proof Pack mission.",
      reflectionPrompt: "Which case would catch the bug fastest if someone changed this code next week?",
      practiceStarter: "const cases = [{ input: { minutes: 30 }, expected: 30 }, { input: { minutes: '' }, expected: 'invalid' }];",
      practiceExpected: "The normal case returns 30, the bad case returns invalid, and the verifier prints passed.",
      practiceCheck: "Check that your harness proves both what should work and what should fail.",
      miniTitle: "Build a two-case regression harness",
      miniGoal: "Create a tiny verifier that preserves one fixed behavior and one rejected bad input.",
      miniSteps: ["Name the behavior that must stay fixed", "Add one normal case", "Add one old-bug or invalid case", "Print passed only after both checks succeed"],
      miniDeliverables: ["Harness code", "Two named cases", "Check output", "Short bug note"],
      verifierCommand: "Run the Code Lab check or node regression_harness.js.",
      expectedEvidence: "Harness code, two named cases, passing check output, and one note describing the bug the harness prevents from returning.",
      projectConnection: "This is the first artifact in the Regression Proof Pack.",
      requiredCodeIncludes: ["summarizeMinutes", "cases"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "const cases = [{ input: { minutes: 30 }, expected: 30 }, { input: { minutes: '' }, expected: 'invalid' }];\n\nfunction summarizeMinutes(input) {\n  return input.minutes;\n}",
      runnerTestCode: "if (summarizeMinutes(cases[0].input) !== 30) throw new Error('normal minutes should pass');\nif (summarizeMinutes(cases[1].input) !== 'invalid') throw new Error('empty minutes should be invalid');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-debugging-failure-log",
      moduleId: "module-testing-debugging-core",
      slug: "debugging-failure-log",
      title: "Failure Logs Make Debugging Reviewable",
      summary: "Capture symptom, hypothesis, fix, verifier, and residual risk for one bug.",
      bodyMarkdown: "A debugging log turns a messy fix into evidence. It helps a reviewer see what failed, what changed, and what still might be untested.",
      estimatedMinutes: 9,
      difficulty: "foundation",
      skillIds: ["skill-debugging-log", "skill-testing-debugging"],
      quizId: "quiz-debugging-failure-log",
      desktopTask: "Write a five-field failure log for a bug you can reproduce with a small input.",
      evidencePrompt: "Capture the failure log and the check output that proves the fix.",
      language: "Debugging",
      tools: ["failure log", "check output", "terminal"],
      synopsis: "You are learning to make debugging visible by recording the symptom, hypothesis, fix, verifier, and remaining risk in one compact artifact.",
      prerequisites: ["Know that a bug has an observed symptom.", "Know that a verifier can prove one narrow behavior."],
      testingFocus: "The check confirms that a useful log includes every field needed for another person to inspect the fix.",
      objective: "Create a debugging log that connects a symptom to a verified fix.",
      whyItMatters: "A clear failure log shows judgment, not just trial-and-error editing.",
      coreConcept: "Debugging evidence ties an observed failure to a hypothesis, a change, and a check result.",
      workedExample: "Symptom: empty minutes crash. Hypothesis: parser trusts blank strings. Fix: reject blanks. Check: empty case returns invalid.",
      guidedExercise: "Fill each log field with one concrete sentence, then check that no field is empty.",
      missionConnection: "This completes the evidence pattern for the Regression Proof Pack mission.",
      reflectionPrompt: "Which remaining risk would you test next if you had another hour?",
      practiceStarter: "const log = { symptom: '', hypothesis: '', fix: '', verifier: '', residualRisk: '' };",
      practiceExpected: "A complete log has all five fields and the verifier prints passed.",
      practiceCheck: "If another person cannot reproduce what failed, the log is not reviewable yet.",
      miniTitle: "Write a reviewable failure log",
      miniGoal: "Create a complete debugging log that explains one verified fix.",
      miniSteps: ["Name the symptom", "Write the hypothesis", "Record the fix", "Attach check output", "Name one residual risk"],
      miniDeliverables: ["Failure log", "Check output", "Residual-risk note"],
      verifierCommand: "Run the Code Lab check or inspect the five-field log.",
      expectedEvidence: "A five-field failure log with symptom, hypothesis, fix, verifier, residual risk, and passing check output.",
      projectConnection: "This becomes the narrative section of the Regression Proof Pack.",
      requiredCodeIncludes: ["symptom", "hypothesis", "verifier"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "const failureLog = { symptom: '', hypothesis: '', fix: '', verifier: '', residualRisk: '' };\n\nfunction isUsefulLog(log) {\n  return false;\n}",
      runnerTestCode: "const good = { symptom: 'blank minutes crash', hypothesis: 'parser trusts blanks', fix: 'reject blank minutes', verifier: 'empty case returns invalid', residualRisk: 'timezone formats not tested' };\nif (!isUsefulLog(good)) throw new Error('complete log should pass');\nif (isUsefulLog({ ...good, verifier: '' })) throw new Error('missing verifier should fail');\nconsole.log('passed');"
    }),
];

export const testingDebuggingQuizzes: Quiz[] = [
  checkpointQuiz("quiz-testing-regression-harness", "lesson-testing-regression-harness", "Regression harness checkpoint", "a regression harness", "Preventing a fixed bug from returning with repeatable checks", "Replacing tests with a screenshot", "Removing failure cases after the fix works", "A regression harness preserves known behavior with a repeatable verifier."),
  checkpointQuiz("quiz-debugging-failure-log", "lesson-debugging-failure-log", "Failure log checkpoint", "a debugging failure log", "Making the symptom, hypothesis, fix, verifier, and residual risk inspectable", "Hiding the failed input after it is fixed", "Claiming debugging is complete without a verifier", "A failure log lets another person understand the debugging path and remaining risk."),
];
