import type { Lesson, LessonPracticeBlock, Quiz } from "@/domain/types";
import { checkpointQuiz, proofLesson } from "../python/shared";

// Cloud Platform Basics track. Mirrors the python/level-N.ts split: this file owns the
// track's lessons and quizzes, and the shared builders in
// src/content/python/shared.ts do the rest.

const cloudReleasePracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const checks = { build: true, tests: true, rollback: false };\nconsole.log(checks);",
    expectedOutput: "Release is blocked because rollback is false.",
    checkYourAnswer: "A rollback note is part of readiness, not paperwork after deploy. Missing rollback should keep the gate closed."
  },
  {
    starterCode: "const checks = { build: true, tests: false, rollback: true };\nconsole.log(checks);",
    expectedOutput: "Release is blocked because tests are false.",
    checkYourAnswer: "This rep prevents build-only thinking. Build success and test success answer different questions."
  },
  {
    starterCode: "const checks = { build: true, tests: true, rollback: true };\nconsole.log(checks);",
    expectedOutput: "Release can proceed because every required gate is true.",
    checkYourAnswer: "All-green means the release is allowed, not guaranteed perfect. The gate controls minimum release evidence."
  }
];

const cloudRollbackPracticeReps: LessonPracticeBlock[] = [
  {
    starterCode: "const release = { version: '1.2.0', previousVersion: '1.1.9', healthCheck: 'failing' };\nfunction rollbackAction(release) {\n  return '';\n}\nconsole.log(rollbackAction(release));",
    expectedOutput: "rollback to 1.1.9 because the health check is failing.",
    checkYourAnswer: "A rollback note must name the exact previous version or action. 'Undo it' is not specific enough."
  },
  {
    starterCode: "const release = { version: '1.2.0', previousVersion: '', healthCheck: 'failing' };\nfunction canRelease(release) {\n  return true;\n}\nconsole.log(canRelease(release));",
    expectedOutput: "false because there is no rollback target.",
    checkYourAnswer: "A release without a rollback target should be blocked before deploy, not discovered after an incident."
  },
  {
    starterCode: "const drill = { trigger: 'error rate > 5%', owner: 'on-call', command: 'deploy previous' };\nconsole.log(drill);",
    expectedOutput: "A rollback drill names trigger, owner, and command.",
    checkYourAnswer: "A useful drill says when to rollback, who acts, and what command or platform action they use."
  }
];

export const cloudPlatformLessons: Lesson[] = [
    proofLesson({
      id: "lesson-cloud-env-config",
      moduleId: "module-cloud-platform-core",
      slug: "cloud-env-config",
      title: "Environment Config Without Secret Leaks",
      summary: "Separate deploy-time settings from secrets and document required environment variables.",
      bodyMarkdown: "Cloud work begins with configuration discipline. A beginner deploy should name required settings and keep private values out of source.",
      estimatedMinutes: 10,
      difficulty: "foundation",
      skillIds: ["skill-cloud-config", "skill-secret-handling"],
      quizId: "quiz-cloud-env-config",
      desktopTask: "Create an environment config matrix for local, preview, and production.",
      evidencePrompt: "Capture the matrix, missing-config behavior, and check output.",
      language: "Cloud platform",
      tools: ["env matrix", "secret boundary", "deploy note"],
      synopsis: "You are learning how deployable apps use environment configuration without copying private values into source code or client bundles.",
      prerequisites: ["Know that apps can run in local and hosted environments.", "Know that secrets should not be committed."],
      testingFocus: "The check confirms that required config exists and that secret values are represented by names, not raw credentials.",
      objective: "Build a small environment config matrix with safe secret handling.",
      whyItMatters: "Config mistakes are one of the fastest ways to break or leak a beginner deployment.",
      coreConcept: "Environment config names required settings while secret values stay in the platform secret store.",
      workedExample: "API_BASE can be documented as a value, but DATABASE_URL should be documented as required without printing the credential.",
      guidedExercise: "Resolve config for local and production, then reject a production config with missing required values.",
      missionConnection: "This starts the Cloud Release Runbook mission.",
      reflectionPrompt: "Which setting would break production if it were missing?",
      practiceStarter: "const env = { NODE_ENV: 'production', API_BASE: 'https://api.example.com', DATABASE_URL: '[secret]' };",
      practiceExpected: "Production config resolves required names without exposing the secret value, and the verifier prints passed.",
      practiceCheck: "The artifact should show what is required, not the real secret.",
      miniTitle: "Create an env config matrix",
      miniGoal: "Document local, preview, and production config without exposing secrets.",
      miniSteps: ["List required variables", "Mark public versus secret settings", "Define missing-config behavior", "Run the config check"],
      miniDeliverables: ["Config matrix", "Missing-config output", "Check output"],
      verifierCommand: "Run the Code Lab check or local config check.",
      expectedEvidence: "Environment matrix, missing-config result, secret-boundary note, and passing check output.",
      projectConnection: "This is the config section of the Cloud Release Runbook.",
      requiredCodeIncludes: ["resolveConfig", "required"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function resolveConfig(env) {\n  return { ok: true, required: [], exposesSecret: true };\n}",
      runnerTestCode: "const prod = resolveConfig({ NODE_ENV: 'production', API_BASE: 'https://api.example.com', DATABASE_URL: '[secret]' });\nif (!prod.ok || prod.exposesSecret) throw new Error('production config should be ok without exposing secrets');\nif (resolveConfig({ NODE_ENV: 'production', API_BASE: '' }).ok) throw new Error('missing production config should fail');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-cloud-ci-deploy-checks",
      moduleId: "module-cloud-platform-core",
      slug: "cloud-ci-deploy-checks",
      title: "Release Checks Before Deploy",
      summary: "Define the checks that must pass before a cloud release is allowed.",
      bodyMarkdown: "A release checklist keeps deployment from being a guess. It should include tests, build, migration or data notes, and rollback readiness.",
      estimatedMinutes: 10,
      difficulty: "applied",
      skillIds: ["skill-ci-release", "skill-testing-debugging"],
      quizId: "quiz-cloud-ci-deploy-checks",
      desktopTask: "Create a release gate that passes only when required checks are green.",
      evidencePrompt: "Capture the required checks, a blocked release example, and a passing release example.",
      language: "Cloud platform",
      tools: ["CI checks", "release gate", "rollback note"],
      synopsis: "You are learning to make release decisions from named checks instead of vibes, screenshots, or a single local run.",
      prerequisites: ["Know that CI can run commands automatically.", "Know that deploys should have rollback notes."],
      testingFocus: "The check confirms that a release is blocked when build, tests, or rollback notes are missing.",
      objective: "Build a release gate that requires build, tests, and rollback readiness.",
      whyItMatters: "Career-ready deploy work includes the evidence that release risk was checked.",
      coreConcept: "A release gate turns required checks into a yes/no deploy decision.",
      workedExample: "If tests pass but rollback is missing, the release should stay blocked.",
      guidedExercise: "Evaluate three check objects and return deploy only when all required checks pass.",
      missionConnection: "This adds deployment gating to the Cloud Release Runbook.",
      reflectionPrompt: "Which missing check should block release most often in this app?",
      practiceStarter: "const checks = { build: true, tests: true, rollback: false };",
      practiceExpected: "A release without rollback is blocked, all-green checks pass, and the verifier prints passed.",
      practiceCheck: "Do not let a single green check hide a missing release requirement.",
      practiceReps: cloudReleasePracticeReps,
      miniTitle: "Build a release gate",
      miniGoal: "Create a function or checklist that blocks deploys until required checks pass.",
      miniSteps: ["Name required checks", "Block one missing-check release", "Allow one all-green release", "Record rollback readiness"],
      miniDeliverables: ["Release gate", "Blocked example", "Passing example"],
      verifierCommand: "Run the Code Lab check or local release-gate test.",
      expectedEvidence: "Release gate artifact, blocked release example, passing release example, rollback note, and check output.",
      projectConnection: "This is the CI gate in the Cloud Release Runbook.",
      requiredCodeIncludes: ["canDeploy", "rollback"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function canDeploy(checks) {\n  return true;\n}",
      runnerTestCode: "if (canDeploy({ build: true, tests: true, rollback: false })) throw new Error('missing rollback should block deploy');\nif (canDeploy({ build: true, tests: false, rollback: true })) throw new Error('failing tests should block deploy');\nif (!canDeploy({ build: true, tests: true, rollback: true })) throw new Error('all checks should deploy');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-cloud-rollback-drill",
      moduleId: "module-cloud-platform-core",
      slug: "cloud-rollback-drill",
      title: "Rollback Drills Before Real Deploys",
      summary: "Practice the exact recovery action before a release needs it.",
      bodyMarkdown: "A rollback plan is weak until someone can follow it under pressure. A beginner-friendly rollback drill names the trigger, previous version, owner, command, and success check. This keeps cloud learning practical: do not just say rollback exists; rehearse the smallest recovery path before the deploy is trusted.",
      estimatedMinutes: 11,
      difficulty: "applied",
      skillIds: ["skill-ci-release", "skill-observability-cost", "skill-testing-debugging"],
      quizId: "quiz-cloud-rollback-drill",
      desktopTask: "Write a rollback drill for one app release with trigger, owner, command, and success check.",
      evidencePrompt: "Capture the rollback drill, blocked release without rollback target, and passing drill check output.",
      language: "Cloud platform",
      tools: ["rollback drill", "release gate", "ops checklist"],
      synopsis: "You are learning to make rollback concrete enough that another person could use it when a release goes wrong.",
      prerequisites: ["Know that deploys can fail after launch.", "Know that a previous version or known-good state must exist before rollback."],
      testingFocus: "The check confirms a drill names trigger, previous version, owner, action, and success check.",
      objective: "Create a rollback drill that names when to rollback and how to confirm recovery.",
      whyItMatters: "Cloud releases are safer when recovery is rehearsed before users are waiting.",
      coreConcept: "A rollback drill turns recovery into a named action with trigger, owner, command, and success check.",
      workedExample: "If error rate exceeds 5%, the owner runs deploy previous 1.1.9, then checks health returns green.",
      guidedExercise: "Fill the five rollback fields, then reject a release that has no previous version.",
      missionConnection: "This deepens the Cloud Release Runbook mission before post-deploy operations.",
      reflectionPrompt: "Which signal would make you rollback instead of continuing to debug in production?",
      practiceStarter: "const drill = { trigger: '', previousVersion: '', owner: '', action: '', successCheck: '' };\nconsole.log(drill);",
      practiceExpected: "The drill has trigger, previous version, owner, action, success check, and the verifier prints passed.",
      practiceCheck: "A rollback note that says investigate is not a rollback action. Name the exact recovery move.",
      practiceReps: cloudRollbackPracticeReps,
      miniTitle: "Write a rollback drill",
      miniGoal: "Create one release recovery drill with a concrete trigger and success check.",
      miniSteps: ["Name rollback trigger", "Name previous version or stable state", "Name owner and action", "Name success check"],
      miniDeliverables: ["Rollback drill", "Blocked no-target example", "Recovery success check"],
      verifierCommand: "Run the Code Lab check or local rollback-drill check.",
      expectedEvidence: "Rollback drill with trigger, owner, previous version, action, success check, plus check output.",
      projectConnection: "This becomes the recovery section of the Cloud Release Runbook.",
      requiredCodeIncludes: ["rollback", "previousVersion", "successCheck"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "const rollbackDrill = { trigger: '', previousVersion: '', owner: '', action: '', successCheck: '' };\n\nfunction drillIsReady(drill) {\n  return false;\n}",
      runnerTestCode: "const ready = { trigger: 'error rate > 5%', previousVersion: '1.1.9', owner: 'release lead', action: 'deploy previous 1.1.9', successCheck: 'health endpoint green' };\nif (!drillIsReady(ready)) throw new Error('complete rollback drill should pass');\nif (drillIsReady({ ...ready, previousVersion: '' })) throw new Error('missing previous version should fail');\nif (drillIsReady({ ...ready, successCheck: '' })) throw new Error('missing success check should fail');\nconsole.log('passed');"
    }),
    proofLesson({
      id: "lesson-cloud-logs-costs",
      moduleId: "module-cloud-platform-core",
      slug: "cloud-logs-costs",
      title: "Logs, Budgets, and Rollback Notes",
      summary: "Summarize basic operations evidence after a deploy: errors, cost signal, and rollback plan.",
      bodyMarkdown: "Deploying is not the end of cloud work. A useful release note includes what to watch, how much it might cost, and how to roll back.",
      estimatedMinutes: 10,
      difficulty: "applied",
      skillIds: ["skill-observability-cost", "skill-ci-release"],
      quizId: "quiz-cloud-logs-costs",
      desktopTask: "Create a post-deploy ops note with log, cost, and rollback fields.",
      evidencePrompt: "Capture the ops note and one check result that checks all required fields.",
      language: "Cloud platform",
      tools: ["logs", "budget note", "rollback note"],
      synopsis: "You are learning to close the loop after deployment by recording what to watch, what it may cost, and how to recover.",
      prerequisites: ["Know that hosted apps produce logs.", "Know that cloud usage can have cost limits."],
      testingFocus: "The check confirms that an ops summary includes error count, cost estimate, and rollback note.",
      objective: "Create a post-deploy operations summary with logs, cost, and rollback evidence.",
      whyItMatters: "Teams trust deploys more when beginners can name what happens after release.",
      coreConcept: "Operations evidence records whether the app is healthy, affordable, and recoverable.",
      workedExample: "A tiny app might note zero startup errors, estimated free-tier use, and the prior commit for rollback.",
      guidedExercise: "Summarize sample events into errors, cost estimate, and rollback note.",
      missionConnection: "This completes the Cloud Release Runbook mission.",
      reflectionPrompt: "Which signal would tell you the release needs rollback?",
      practiceStarter: "const events = [{ level: 'info' }, { level: 'error' }];",
      practiceExpected: "The ops summary includes errors, cost, rollback, and the verifier prints passed.",
      practiceCheck: "A deployment screenshot alone does not prove the app is healthy or recoverable.",
      miniTitle: "Write a post-deploy ops note",
      miniGoal: "Create an operations summary with log, budget, and rollback fields.",
      miniSteps: ["Summarize logs", "Estimate cost tier", "Name rollback action", "Record the check output"],
      miniDeliverables: ["Ops summary", "Cost note", "Rollback note"],
      verifierCommand: "Run the Code Lab check or inspect the ops summary.",
      expectedEvidence: "Post-deploy ops summary with log health, cost note, rollback action, and passing check output.",
      projectConnection: "This closes the Cloud Release Runbook with operations evidence.",
      requiredCodeIncludes: ["summarizeOps", "rollback"],
      requiredOutputIncludes: ["passed"],
      runnerStarterCode: "function summarizeOps(events) {\n  return { errors: 0, costNote: '', rollback: '' };\n}",
      runnerTestCode: "const summary = summarizeOps([{ level: 'info' }, { level: 'error' }]);\nif (summary.errors !== 1) throw new Error('should count one error');\nif (!summary.costNote || !summary.rollback) throw new Error('cost and rollback notes are required');\nconsole.log('passed');"
    }),
];

export const cloudPlatformQuizzes: Quiz[] = [
  checkpointQuiz("quiz-cloud-env-config", "lesson-cloud-env-config", "Cloud config checkpoint", "environment configuration", "Documenting required settings while keeping secret values out of source", "Committing production credentials to simplify deploys", "Assuming local defaults are enough for production", "Cloud config needs explicit required values and secret boundaries."),
  checkpointQuiz("quiz-cloud-ci-deploy-checks", "lesson-cloud-ci-deploy-checks", "Release checks checkpoint", "a release gate", "Blocking deploy until required build, test, and rollback checks pass", "Deploying because one local command worked", "Skipping rollback because the change is small", "A release gate converts deploy readiness into named evidence."),
  checkpointQuiz("quiz-cloud-rollback-drill", "lesson-cloud-rollback-drill", "Rollback drill checkpoint", "a rollback drill", "Naming trigger, owner, previous version, action, and success check before deploy", "Inventing rollback steps during the incident", "Shipping without a previous version or owner", "Rollback drills make recovery concrete before a release needs it."),
  checkpointQuiz("quiz-cloud-logs-costs", "lesson-cloud-logs-costs", "Ops note checkpoint", "post-deploy operations evidence", "Recording health, cost signal, and rollback action after release", "Saving only a launch screenshot", "Ignoring budget because the app is small", "Post-deploy evidence shows whether the release is healthy and recoverable."),
];
