import type { ContentPack, ProjectMissionPhase } from "@/domain/types";
import {
  balanceQuizChoices,
  foundationEvidence,
  normalizeQuizPassingScore,
  portfolioEvidence,
} from "./python/shared";
import { level0Lessons, level0Quizzes } from "./python/level-0";
import { level1Lessons, level1Quizzes, deprecatedLevel1Lessons } from "./python/level-1";
import { level2Lessons, level2Quizzes } from "./python/level-2";
import { level3Lessons, level3Quizzes, deprecatedLevel3Lessons } from "./python/level-3";
import { level4Lessons, level4Quizzes, deprecatedLevel4Lessons } from "./python/level-4";
import { level5Lessons, level5Quizzes } from "./python/level-5";
import { level6Lessons, level6Quizzes } from "./python/level-6";
import { level7Lessons, level7Quizzes } from "./python/level-7";
import { level8Lessons, level8Quizzes } from "./python/level-8";
import { level9Lessons, level9Quizzes } from "./python/level-9";
import { aiAppsLessons, aiAppsQuizzes } from "./ai-apps/lessons";
import { aiToolsLessons, aiToolsQuizzes } from "./ai-tools/lessons";
import { cloudPlatformLessons, cloudPlatformQuizzes } from "./cloud-platform-basics/lessons";
import { dataSystemsLessons, dataSystemsQuizzes } from "./data-systems/lessons";
import { gitLessons, gitQuizzes } from "./git/lessons";
import { mlLessons, mlQuizzes } from "./ml/lessons";
import { secureSoftwareLessons, secureSoftwareQuizzes } from "./secure-software/lessons";
import { sqlLessons, sqlQuizzes } from "./sql/lessons";
import { testingDebuggingLessons, testingDebuggingQuizzes } from "./testing-debugging/lessons";
import { typescriptLessons, typescriptQuizzes } from "./typescript/lessons";

function missionPhases(slug: string, buildTarget: string, verifier: string, polishTarget = "portfolio note"): ProjectMissionPhase[] {
  return [
    {
      id: `${slug}-plan`,
      title: "Plan the check",
      goal: `Define the smallest useful version of ${buildTarget}.`,
      tasks: ["Write the user story", "List the data contract", "Name the check before building"]
    },
    {
      id: `${slug}-build`,
      title: "Build the slice",
      goal: `Create ${buildTarget} with one complete happy path and one handled failure path.`,
      tasks: ["Implement the core flow", "Keep UI or CLI separate from domain logic", "Commit when the first slice works"]
    },
    {
      id: `${slug}-verify`,
      title: "Verify and explain",
      goal: `Confirm ${buildTarget} works with ${verifier}.`,
      tasks: ["Run the check", "Capture exact output", `Write the ${polishTarget}`]
    }
  ];
}

export const contentPack: ContentPack = {
  skills: [
    { id: "skill-git-workflow", slug: "git-workflow", name: "Git workflow", category: "workflow" },
    { id: "skill-python-basics", slug: "python-basics", name: "Python basics", category: "language" },
    { id: "skill-python-functions", slug: "python-functions", name: "Python functions", category: "language" },
    { id: "skill-python-professional", slug: "python-professional", name: "Professional Python", category: "language" },
    { id: "skill-python-integration", slug: "python-integration", name: "Python integration", category: "backend" },
    { id: "skill-typescript-types", slug: "typescript-types", name: "TypeScript types", category: "language" },
    { id: "skill-sql-joins", slug: "sql-joins", name: "SQL joins", category: "data" },
    { id: "skill-api-contracts", slug: "api-contracts", name: "API contracts", category: "backend" },
    { id: "skill-testing-debugging", slug: "testing-debugging", name: "Testing and debugging", category: "workflow" },
    { id: "skill-regression-testing", slug: "regression-testing", name: "Regression testing", category: "workflow" },
    { id: "skill-debugging-log", slug: "debugging-log", name: "Debugging evidence logs", category: "workflow" },
    { id: "skill-threat-modeling", slug: "threat-modeling", name: "Threat modeling", category: "backend" },
    { id: "skill-secret-handling", slug: "secret-handling", name: "Secret handling", category: "backend" },
    { id: "skill-auth-boundaries", slug: "auth-boundaries", name: "Auth boundaries", category: "backend" },
    { id: "skill-dependency-hygiene", slug: "dependency-hygiene", name: "Dependency hygiene", category: "workflow" },
    { id: "skill-cloud-config", slug: "cloud-config", name: "Cloud configuration", category: "backend" },
    { id: "skill-ci-release", slug: "ci-release", name: "CI and release checks", category: "workflow" },
    { id: "skill-observability-cost", slug: "observability-cost", name: "Observability and cost notes", category: "backend" },
    { id: "skill-data-quality", slug: "data-quality", name: "Data quality", category: "data" },
    { id: "skill-data-pipelines", slug: "data-pipelines", name: "Data pipelines", category: "data" },
    { id: "skill-reproducible-report", slug: "reproducible-report", name: "Reproducible reporting", category: "data" },
    { id: "skill-ai-verification", slug: "ai-verification", name: "AI output verification", category: "ai" },
    { id: "skill-portfolio-evidence", slug: "portfolio-evidence", name: "Portfolio evidence", category: "portfolio" },
    { id: "skill-ml-metrics", slug: "ml-metrics", name: "ML metrics", category: "ai" }
  ],
  skillEdges: [
    { fromSkillId: "skill-git-workflow", toSkillId: "skill-portfolio-evidence", relationType: "supports" },
    { fromSkillId: "skill-python-basics", toSkillId: "skill-python-functions", relationType: "prerequisite" },
    { fromSkillId: "skill-python-functions", toSkillId: "skill-python-professional", relationType: "prerequisite" },
    { fromSkillId: "skill-python-professional", toSkillId: "skill-python-integration", relationType: "prerequisite" },
    { fromSkillId: "skill-python-functions", toSkillId: "skill-api-contracts", relationType: "supports" },
    { fromSkillId: "skill-testing-debugging", toSkillId: "skill-ai-verification", relationType: "prerequisite" },
    { fromSkillId: "skill-testing-debugging", toSkillId: "skill-regression-testing", relationType: "extends" },
    { fromSkillId: "skill-regression-testing", toSkillId: "skill-debugging-log", relationType: "supports" },
    { fromSkillId: "skill-sql-joins", toSkillId: "skill-api-contracts", relationType: "supports" },
    { fromSkillId: "skill-api-contracts", toSkillId: "skill-threat-modeling", relationType: "supports" },
    { fromSkillId: "skill-threat-modeling", toSkillId: "skill-secret-handling", relationType: "prerequisite" },
    { fromSkillId: "skill-secret-handling", toSkillId: "skill-auth-boundaries", relationType: "supports" },
    { fromSkillId: "skill-testing-debugging", toSkillId: "skill-dependency-hygiene", relationType: "supports" },
    { fromSkillId: "skill-api-contracts", toSkillId: "skill-cloud-config", relationType: "supports" },
    { fromSkillId: "skill-cloud-config", toSkillId: "skill-ci-release", relationType: "supports" },
    { fromSkillId: "skill-ci-release", toSkillId: "skill-observability-cost", relationType: "extends" },
    { fromSkillId: "skill-sql-joins", toSkillId: "skill-data-quality", relationType: "supports" },
    { fromSkillId: "skill-data-quality", toSkillId: "skill-data-pipelines", relationType: "supports" },
    { fromSkillId: "skill-data-pipelines", toSkillId: "skill-reproducible-report", relationType: "extends" }
  ],
  tracks: [
    {
      id: "track-python",
      slug: "python-fundamentals",
      title: "Python Fundamentals",
      summary: "Small automation, professional structure, typed models, logs, and tests for real project proof.",
      roleTargets: ["Software Foundations", "Backend, APIs & Data Systems"],
      moduleIds: ["module-python-core", "module-python-professional", "module-python-dashboard", "module-python-api-resilience", "module-python-ops"],
      accentColor: "#0B2F6A"
    },
    {
      id: "track-typescript",
      slug: "typescript-web",
      title: "TypeScript and Web",
      summary: "Typed UI thinking, API-shaped data, and browser problem solving.",
      roleTargets: ["Software Foundations", "AI Product Engineering"],
      moduleIds: ["module-typescript-core"],
      accentColor: "#2B7BFF"
    },
    {
      id: "track-sql",
      slug: "sql-postgres",
      title: "SQL and Postgres",
      summary: "Queries, joins, schema thinking, and persistence for app builders.",
      roleTargets: ["Backend, APIs & Data Systems", "Secure Software & AppSec"],
      moduleIds: ["module-sql-core", "module-sql-querying", "module-sql-modeling"],
      accentColor: "#08234F"
    },
    {
      id: "track-git",
      slug: "git-github",
      title: "Git and GitHub",
      summary: "Repository hygiene, commits, READMEs, issues, and release evidence.",
      roleTargets: ["Software Foundations", "Secure Software & AppSec"],
      moduleIds: ["module-git-core"],
      accentColor: "#1DA28F"
    },
    {
      id: "track-ai-tools",
      slug: "ai-assisted-coding",
      title: "AI-Assisted Coding",
      summary: "Use AI for speed while preserving tests, review, and ownership.",
      roleTargets: ["Software Foundations", "AI Product Engineering"],
      moduleIds: ["module-ai-verification"],
      accentColor: "#1A67E8"
    },
    {
      id: "track-testing-debugging",
      slug: "testing-debugging",
      title: "Testing and Debugging",
      summary: "Regression checks, failure logs, and readable check output before specialization.",
      roleTargets: ["Software Foundations", "Shared Core Readiness"],
      moduleIds: ["module-testing-debugging-core"],
      accentColor: "#6B5B95"
    },
    {
      id: "track-secure-software",
      slug: "secure-software-appsec",
      title: "Secure Software",
      summary: "Threat notes, secret handling, auth boundaries, input validation, dependency hygiene, and safe logging.",
      roleTargets: ["Secure Software & AppSec"],
      moduleIds: ["module-secure-software-core"],
      accentColor: "#8A1C32"
    },
    {
      id: "track-ai-apps",
      slug: "practical-ai-apps",
      title: "Practical AI Apps",
      summary: "Plan RAG, evals, routers, and safety checks without shipping secrets.",
      roleTargets: ["AI Product Engineering", "Backend unlock"],
      moduleIds: ["module-ai-apps"],
      accentColor: "#D1433A"
    },
    {
      id: "track-ml",
      slug: "ml-foundations",
      title: "ML Foundations",
      summary: "Data splits, metrics, error analysis, and responsible model summaries.",
      roleTargets: ["Backend/Data unlock", "ML & Model Literacy"],
      moduleIds: ["module-ml-core"],
      accentColor: "#157A6E"
    },
    {
      id: "track-cloud-platform-basics",
      slug: "cloud-platform-basics",
      title: "Cloud Platform Basics",
      summary: "Environment config, CI release checks, logs, budgets, and rollback notes for beginner deployable work.",
      roleTargets: ["Backend unlock", "Security unlock"],
      moduleIds: ["module-cloud-platform-core"],
      accentColor: "#4A6FA5"
    },
    {
      id: "track-data-systems",
      slug: "data-systems",
      title: "Data Systems",
      summary: "Data quality, pipeline lineage, reproducible reports, and product-facing data evidence.",
      roleTargets: ["Backend unlock", "Data unlock"],
      moduleIds: ["module-data-systems-core"],
      accentColor: "#2E6F40"
    }
  ],
  modules: [
    {
      id: "module-python-core",
      trackId: "track-python",
      slug: "python-core",
      title: "Python Core",
      summary: "Beginner syntax, debugging, text cleanup, functions, files, tests, and a testable command-line utility.",
      lessonIds: [
        // Level 0 — Environment orientation
        "lesson-python-zero-files-folders",
        "lesson-python-zero-terminal",
        "lesson-python-zero-first-script",
        "lesson-python-zero-change-rerun",
        "lesson-python-zero-first-error",
        // Level 1 — Values and output (micro-lessons)
        "lesson-python-literals",
        "lesson-python-assignment",
        "lesson-python-print-values",
        "lesson-python-numbers",
        "lesson-python-strings",
        "lesson-python-fstrings",
        // Level 2 — Collections, decisions, loops, capstone
        "lesson-python-lists",
        "lesson-python-dicts",
        "lesson-python-list-of-dicts",
        "lesson-python-strings-cleanup",
        "lesson-python-decisions",
        "lesson-python-loops",
        "lesson-python-foundation-capstone",
        "lesson-python-module-guard",
        // Level 3 — Functions (micro-lessons)
        "lesson-python-why-functions",
        "lesson-python-def-call",
        "lesson-python-parameters",
        "lesson-python-return",
        "lesson-python-print-vs-return",
        "lesson-python-functions-capstone",
        // Level 4 — Debugging (micro-lessons)
        "lesson-python-read-traceback",
        "lesson-python-nameerror",
        "lesson-python-typeerror",
        "lesson-python-valueerror",
        "lesson-python-try-except",
        "lesson-python-breakpoint-debugger",
        "lesson-python-assertions",
        "lesson-python-debugging-capstone",
        // Level 5+ — Import, files, parser, CLI, portfolio
        "lesson-python-import",
        "lesson-python-file-input",
        "lesson-python-parser-tests",
        "lesson-python-cli-arguments",
        "lesson-python-file-backed-cli",
        "lesson-python-cli-polish",
        "lesson-python-output-file",
        "lesson-python-rejected-row-report",
        "lesson-python-portfolio-proof",
        "lesson-python-core-review"
      ],
      projectMissionIds: ["mission-cli-study-tracker", "mission-python-data-cleaner"],
      skillIds: ["skill-python-basics", "skill-python-functions", "skill-testing-debugging"],
      sortOrder: 1
    },
    {
      id: "module-python-professional",
      trackId: "track-python",
      slug: "python-professional",
      title: "Professional Python Utility",
      summary: "Structure, typed models, JSON reports, logging, packaging, configuration, and CI evidence for reviewable Python work.",
      lessonIds: ["lesson-python-project-structure", "lesson-python-dataclass-models", "lesson-python-json-reports", "lesson-python-logging-errors", "lesson-python-pytest-ci", "lesson-python-pyproject-metadata", "lesson-python-installable-cli", "lesson-python-virtual-env", "lesson-python-config-files", "lesson-python-ci-precommit", "lesson-python-professional-review"],
      projectMissionIds: ["mission-professional-python-utility"],
      skillIds: ["skill-python-professional", "skill-python-functions", "skill-testing-debugging", "skill-portfolio-evidence"],
      sortOrder: 2
    },
    {
      id: "module-python-dashboard",
      trackId: "track-python",
      slug: "python-dashboard",
      title: "Python Study Dashboard",
      summary: "SQLite persistence, API sync, object-oriented services, regex validation, and a complete dashboard proof artifact.",
      lessonIds: ["lesson-python-type-hints", "lesson-python-regex-validation", "lesson-python-oop-service", "lesson-python-sqlite-persistence", "lesson-python-api-client", "lesson-python-testing-mocks", "lesson-python-integration-capstone", "lesson-python-integration-review"],
      projectMissionIds: ["mission-python-integration-service"],
      skillIds: ["skill-python-integration", "skill-python-professional", "skill-testing-debugging", "skill-api-contracts", "skill-sql-joins"],
      sortOrder: 3
    },
    {
      id: "module-python-api-resilience",
      trackId: "track-python",
      slug: "python-api-resilience",
      title: "API Resilience & Retry",
      summary: "Retry logic, rate limiting, caching, and circuit breaker patterns for professional resilient Python services.",
      lessonIds: ["lesson-python-api-retry", "lesson-python-rate-limiting", "lesson-python-api-caching", "lesson-python-circuit-breaker"],
      projectMissionIds: ["mission-python-api-resilience"],
      skillIds: ["skill-python-integration", "skill-api-contracts", "skill-testing-debugging"],
      sortOrder: 4
    },
    {
      id: "module-python-ops",
      trackId: "track-python",
      slug: "python-ops",
      title: "Operations & CI/CD",
      summary: "Environment configuration, secrets management, CI workflows, deployment strategies, and monitoring for professional Python.",
      lessonIds: ["lesson-python-env-config", "lesson-python-ci-workflow", "lesson-python-secrets-management", "lesson-python-deployment-strategies", "lesson-python-monitoring-basics"],
      projectMissionIds: ["mission-python-ops"],
      skillIds: ["skill-python-professional", "skill-secret-handling", "skill-ci-release"],
      sortOrder: 5
    },
    {
      id: "module-typescript-core",
      trackId: "track-typescript",
      slug: "typescript-core",
      title: "TypeScript App Thinking",
      summary: "Model domain objects before wiring screens.",
      lessonIds: ["lesson-typescript-contracts", "lesson-typescript-runtime-validation", "lesson-typescript-events-state"],
      projectMissionIds: ["mission-web-progress-board", "mission-api-contract-playground"],
      skillIds: ["skill-typescript-types", "skill-api-contracts"],
      sortOrder: 1
    },
    {
      id: "module-sql-core",
      trackId: "track-sql",
      slug: "sql-core",
      title: "SQL for App State",
      summary: "Use joins to answer product questions from normalized data.",
      lessonIds: ["lesson-sql-joins", "lesson-sql-constraints"],
      projectMissionIds: ["mission-sql-portfolio-ledger", "mission-job-tracker-schema"],
      skillIds: ["skill-sql-joins"],
      sortOrder: 1
    },
    {
      id: "module-sql-querying",
      trackId: "track-sql",
      slug: "sql-querying",
      title: "SQL Querying",
      summary: "Aggregate, filter with subqueries, name steps with CTEs, and add per-row windows.",
      lessonIds: [
        "lesson-sql-aggregates",
        "lesson-sql-subqueries",
        "lesson-sql-ctes",
        "lesson-sql-window-functions",
        "lesson-sql-join-fanout"
      ],
      projectMissionIds: ["mission-sql-portfolio-ledger", "mission-job-tracker-schema"],
      skillIds: ["skill-sql-joins", "skill-data-quality"],
      sortOrder: 2
    },
    {
      id: "module-sql-modeling",
      trackId: "track-sql",
      slug: "sql-modeling",
      title: "SQL Data Modeling",
      summary: "Keep one fact in one place and reference it by key so reports stay consistent.",
      lessonIds: ["lesson-sql-normalization"],
      projectMissionIds: ["mission-job-tracker-schema"],
      skillIds: ["skill-sql-joins", "skill-data-quality"],
      sortOrder: 3
    },
    {
      id: "module-git-core",
      trackId: "track-git",
      slug: "git-core",
      title: "GitHub Evidence",
      summary: "Turn local work into proof a reviewer can inspect.",
      lessonIds: ["lesson-git-evidence", "lesson-github-review-flow"],
      projectMissionIds: ["mission-portfolio-readme"],
      skillIds: ["skill-git-workflow", "skill-portfolio-evidence"],
      sortOrder: 1
    },
    {
      id: "module-ai-verification",
      trackId: "track-ai-tools",
      slug: "ai-verification",
      title: "AI With Verification",
      summary: "Use model help while keeping tests and source custody.",
      lessonIds: ["lesson-ai-test-loop", "lesson-ai-diff-review"],
      projectMissionIds: ["mission-ai-bug-rubric", "mission-ai-test-harness"],
      skillIds: ["skill-ai-verification", "skill-testing-debugging"],
      sortOrder: 1
    },
    {
      id: "module-testing-debugging-core",
      trackId: "track-testing-debugging",
      slug: "testing-debugging-core",
      title: "Testing and Debugging",
      summary: "Build a tiny regression harness and a failure log that make debugging visible.",
      lessonIds: ["lesson-testing-regression-harness", "lesson-debugging-failure-log"],
      projectMissionIds: ["mission-regression-proof-pack"],
      skillIds: ["skill-testing-debugging", "skill-regression-testing", "skill-debugging-log", "skill-portfolio-evidence"],
      sortOrder: 1
    },
    {
      id: "module-secure-software-core",
      trackId: "track-secure-software",
      slug: "secure-software-core",
      title: "Secure Software Practice",
      summary: "Practice concrete AppSec habits: threat modeling, secrets, auth boundaries, validation, dependencies, and logs.",
      lessonIds: ["lesson-security-threat-model", "lesson-security-secrets-auth", "lesson-security-access-control-lab", "lesson-security-input-validation", "lesson-security-injection-output-encoding", "lesson-security-dependency-logging"],
      projectMissionIds: ["mission-secure-review-pack"],
      skillIds: ["skill-threat-modeling", "skill-secret-handling", "skill-auth-boundaries", "skill-dependency-hygiene", "skill-testing-debugging", "skill-portfolio-evidence"],
      sortOrder: 1
    },
    {
      id: "module-ai-apps",
      trackId: "track-ai-apps",
      slug: "ai-apps",
      title: "AI App Foundations",
      summary: "Design AI features behind safe server boundaries.",
      lessonIds: ["lesson-ai-app-boundaries", "lesson-ai-retrieval-grounding"],
      projectMissionIds: ["mission-ai-study-planner", "mission-rag-notes-prototype"],
      skillIds: ["skill-ai-verification", "skill-api-contracts"],
      sortOrder: 1
    },
    {
      id: "module-ml-core",
      trackId: "track-ml",
      slug: "ml-core",
      title: "ML Metrics Basics",
      summary: "Explain a model result with splits, metrics, and limits.",
      lessonIds: ["lesson-ml-metrics", "lesson-ml-confusion-matrix"],
      projectMissionIds: ["mission-ml-metrics-report"],
      skillIds: ["skill-ml-metrics", "skill-testing-debugging"],
      sortOrder: 1
    },
    {
      id: "module-cloud-platform-core",
      trackId: "track-cloud-platform-basics",
      slug: "cloud-platform-core",
      title: "Cloud Platform Practice",
      summary: "Prepare deployable work with environment config, CI release checks, logs, budget notes, and rollback evidence.",
      lessonIds: ["lesson-cloud-env-config", "lesson-cloud-ci-deploy-checks", "lesson-cloud-rollback-drill", "lesson-cloud-logs-costs"],
      projectMissionIds: ["mission-cloud-release-runbook"],
      skillIds: ["skill-cloud-config", "skill-ci-release", "skill-observability-cost", "skill-portfolio-evidence"],
      sortOrder: 1
    },
    {
      id: "module-data-systems-core",
      trackId: "track-data-systems",
      slug: "data-systems-core",
      title: "Data Systems Practice",
      summary: "Turn messy records into quality checks, lineage notes, and reproducible product-facing reports.",
      lessonIds: ["lesson-data-quality-rules", "lesson-data-contracts-fixtures", "lesson-data-rejected-row-proof", "lesson-data-pipeline-lineage", "lesson-data-reproducible-report"],
      projectMissionIds: ["mission-data-quality-report"],
      skillIds: ["skill-data-quality", "skill-data-pipelines", "skill-reproducible-report", "skill-sql-joins", "skill-portfolio-evidence"],
      sortOrder: 1
    }
  ],
  lessons: [
    ...level0Lessons,
    ...level1Lessons,
    ...deprecatedLevel1Lessons,
    ...level2Lessons,
    ...level3Lessons,
    ...deprecatedLevel3Lessons,
    ...level4Lessons,
    ...deprecatedLevel4Lessons,
    ...level5Lessons,
    ...level6Lessons,
    ...level7Lessons,
    ...level8Lessons,
    ...level9Lessons,
    ...typescriptLessons,
    ...sqlLessons,
    ...gitLessons,
    ...aiToolsLessons,
    ...aiAppsLessons,
    ...mlLessons,
    ...testingDebuggingLessons,
    ...secureSoftwareLessons,
    ...cloudPlatformLessons,
    ...dataSystemsLessons,
  ],
  quizzes: [
    ...level0Quizzes,
    ...level1Quizzes,
    ...level2Quizzes,
    ...level3Quizzes,
    ...level4Quizzes,
    ...level5Quizzes,
    ...level6Quizzes,
    ...level7Quizzes,
    ...level8Quizzes,
    ...level9Quizzes,
    ...typescriptQuizzes,
    ...sqlQuizzes,
    ...gitQuizzes,
    ...aiToolsQuizzes,
    ...aiAppsQuizzes,
    ...mlQuizzes,
    ...testingDebuggingQuizzes,
    ...secureSoftwareQuizzes,
    ...cloudPlatformQuizzes,
    ...dataSystemsQuizzes,
  ].map(normalizeQuizPassingScore).map(balanceQuizChoices),
  projectMissions: [
    {
      id: "mission-cli-study-tracker",
      trackId: "track-python",
      title: "CLI Study Tracker",
      brief: "Build a small Python command-line tool that records study sessions and prints weekly totals.",
      difficulty: "foundation",
      deliverables: ["Python script", "README run instructions", "Two tests or assertion examples"],
      acceptanceCriteria: ["Tracks at least date, topic, and minutes", "Handles bad input with a clear message", "Includes --help, documented defaults, report output, and verification output"],
      phases: missionPhases("cli-study-tracker", "a CLI study tracker", "pytest or documented assertions"),
      starterPrompt: "Build a Python CLI that accepts study sessions, stores them in a small local file, and prints weekly totals by topic.",
      verificationCommands: ["python study_tracker.py --help", "python study_tracker.py --input sessions.csv --output summary.txt", "pytest"],
      expectedArtifacts: ["Repository link", "Sample input file", "--help output", "summary.txt output", "Check output", "README usage section"],
      rubric: ["Input validation is explicit", "Core grouping logic is testable without terminal output", "CLI help and defaults are reviewer-friendly", "README states known limits"],
      commonFailureModes: ["Mixing parsing, printing, and storage in one function", "Only testing the happy path", "Leaving CLI defaults undocumented", "Claiming passing tests without command output"],
      portfolioSummaryPrompt: "Explain how this project proves Python functions, file input, and test/debug discipline.",
      // Beginner missions must not require Git/GitHub evidence before any
      // lesson teaches it (content-integrity Rule Group D). Learners can still
      // attach repo evidence voluntarily; it is not required to complete.
      evidenceRequirements: { ...foundationEvidence, repoUrl: false },
      skillIds: ["skill-python-functions", "skill-testing-debugging", "skill-portfolio-evidence"],
      curriculum: {
        level: 0,
        missionType: "cli",
        requires: [],
        supportedLessonIds: [
          "lesson-python-zero-files-folders",
          "lesson-python-zero-terminal",
          "lesson-python-zero-first-script",
          "lesson-python-zero-change-rerun",
          "lesson-python-zero-first-error",
          "lesson-python-literals",
          "lesson-python-assignment",
          "lesson-python-fstrings",
          "lesson-python-print-values",
          "lesson-python-numbers",
          "lesson-python-strings",
          "lesson-python-values"
        ],
        proofOutputs: ["terminal_stdout", "test_output", "readme"]
      }
    },
    {
      id: "mission-python-data-cleaner",
      trackId: "track-python",
      title: "Study Data Cleaner",
      brief: "Turn messy session notes into normalized weekly records with rejected-row reporting.",
      difficulty: "applied",
      deliverables: ["Parser module", "Rejected-row report", "Unit tests for malformed input"],
      acceptanceCriteria: ["Separates parsing from reporting", "Rejects bad rows with row numbers and reasons", "Produces deterministic weekly totals"],
      phases: missionPhases("python-data-cleaner", "a small data cleaner", "unit tests against clean and malformed rows"),
      starterPrompt: "Create a Python module that reads messy study records, normalizes fields, rejects malformed rows, and returns a summary object.",
      verificationCommands: ["python -m pytest", "python clean_sessions.py samples/messy_sessions.csv --rejected rejected_rows.txt"],
      expectedArtifacts: ["Repo URL", "Sample messy input", "Rejected-row report", "Check output"],
      rubric: ["Bad data does not crash the app", "Rejected rows include row numbers, raw rows, and reasons", "Tests prove both accepted and rejected rows", "Reflection names the edge case that took longest"],
      commonFailureModes: ["Silently dropping bad rows", "Reporting bad rows without enough context to fix them", "Hardcoding sample data into code", "Printing results that tests cannot inspect"],
      portfolioSummaryPrompt: "Summarize the data-quality problem, the parser contract, and the failure cases you handled.",
      evidenceRequirements: { ...foundationEvidence, repoUrl: false },
      skillIds: ["skill-python-functions", "skill-testing-debugging", "skill-portfolio-evidence"],
      curriculum: {
        level: 1,
        missionType: "file_processing",
        requires: [],
        supportedLessonIds: [
          "lesson-python-literals",
          "lesson-python-assignment",
          "lesson-python-fstrings",
          "lesson-python-print-values",
          "lesson-python-numbers",
          "lesson-python-strings",
          "lesson-python-values",
          "lesson-python-lists",
          "lesson-python-dicts",
          "lesson-python-list-of-dicts"
        ],
        proofOutputs: ["csv_sample", "test_output", "readme"]
      }
    },
    {
      id: "mission-professional-python-utility",
      trackId: "track-python",
      title: "Professional Python Utility",
      brief: "Turn the study tracker into an installable, reviewable Python package with typed models, JSON output, config, logging, and CI-grade evidence.",
      difficulty: "portfolio",
      deliverables: ["Python package layout", "pyproject.toml", "Installable CLI entry point", "Typed StudySession model", "JSON report mode", "Config loader", "Logged custom errors", "Pytest and CI/pre-commit evidence"],
      acceptanceCriteria: ["Package separates CLI, parsing, models, and reports", "pyproject.toml declares project metadata and console script", "Invalid input raises project-specific errors and logs context", "JSON output has stable fields", "Config merges defaults predictably", "README includes exact pytest, pre-commit, and installed CLI smoke commands"],
      phases: missionPhases("professional-python-utility", "an installable professional Python CLI utility", "python -m pytest plus installed CLI smoke commands", "portfolio README"),
      starterPrompt: "Refactor the study tracker into a package with pyproject.toml, cli.py, parser.py, models.py, reports.py, config loading, tests, JSON output, custom errors, logging, and CI/pre-commit verification commands.",
      verificationCommands: ["python -m pytest", "python -m pip install -e .", "study-tracker --help", "study-tracker --input sessions.csv --format json", "pre-commit run --all-files"],
      expectedArtifacts: ["Package file tree", "pyproject.toml", "Sample input files", "JSON output", "Config example", "Log/error example", "Pytest output", "Pre-commit or CI output", "README verification section"],
      rubric: ["Module boundaries are clear", "Package metadata and entry point are defined", "Data model validates impossible values", "JSON fields are stable and tested", "Config defaults are explicit", "Errors are logged without hiding failures", "Verification commands are reproducible"],
      commonFailureModes: ["Keeping all behavior in one script", "No installable command", "Returning fake values for bad input", "Changing JSON field names without tests", "Config values overriding unknown behavior", "Logging no useful context", "README claims pass without exact output"],
      portfolioSummaryPrompt: "Explain how this project demonstrates professional Python packaging, typed data modeling, machine-readable output, configuration, logging, and repeatable CI-grade verification.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-python-professional", "skill-python-functions", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-python-integration-service",
      trackId: "track-python",
      title: "Python Integration Service",
      brief: "Extend the professional tracker with regex validation, service classes, SQLite persistence, safe API boundaries, and integration evidence.",
      difficulty: "portfolio",
      deliverables: ["Regex validation tests", "StudyTrackerService class", "SQLite schema and queries", "Safe API client tests", "Integration verification matrix"],
      acceptanceCriteria: ["Regex validators reject malformed date and slug input", "Service instances do not share mutable state", "SQLite queries calculate topic totals from stored rows", "API client checks timeout, status, and response shape", "Integration matrix maps every layer to tests and evidence"],
      phases: missionPhases("python-integration-service", "an integrated Python utility service", "unit tests plus CLI and database smoke commands", "portfolio architecture note"),
      starterPrompt: "Extend the professional study tracker with regex validation, an OOP service layer, SQLite persistence, a safe API client boundary, and a final integration verification matrix.",
      verificationCommands: ["python -m pytest", "sqlite3 tracker.db < schema_and_query.sql", "study-tracker --input sessions.csv --format json", "study-tracker --help"],
      expectedArtifacts: ["Validation test output", "Service tests", "SQLite schema/query output", "API client tests", "Integration matrix", "CLI smoke output"],
      rubric: ["Regex stays focused and tested", "Service state is isolated", "Persistence schema answers real questions", "API boundary validates untrusted responses", "Integration evidence covers every layer"],
      commonFailureModes: ["Regex doing too much parsing", "Shared class-level mutable state", "Database schema with no useful query", "API client trusting raw JSON", "Capstone evidence proving only the happy path"],
      portfolioSummaryPrompt: "Explain how the project demonstrates integrated Python engineering: validation, OOP services, persistence, API safety, and layered verification.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-python-integration", "skill-python-professional", "skill-testing-debugging", "skill-api-contracts", "skill-sql-joins", "skill-portfolio-evidence"]
    },
    {
      id: "mission-web-progress-board",
      trackId: "track-typescript",
      title: "Typed Progress Board",
      brief: "Create a TypeScript UI mock that renders tracks, progress, and next actions from typed data.",
      difficulty: "foundation",
      deliverables: ["Typed data model", "Rendered board", "Screenshot or short demo"],
      acceptanceCriteria: ["No implicit any types", "Progress data is not hardcoded into UI elements", "README explains the data contract"],
      phases: missionPhases("web-progress-board", "a typed progress board", "typecheck plus a screenshot or demo"),
      starterPrompt: "Build a small TypeScript progress board that renders track cards from typed seed data and highlights the next action.",
      verificationCommands: ["npm run typecheck", "npm run test"],
      expectedArtifacts: ["Type definitions", "Screenshot or demo link", "Check output", "README data contract section"],
      rubric: ["Types describe the domain before UI", "Cards render from data arrays", "Empty or missing progress has a visible state"],
      commonFailureModes: ["Hardcoding every card", "Using broad any types", "Showing percentages without explaining the source"],
      portfolioSummaryPrompt: "Explain how this proves typed UI modeling and data-driven rendering.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-typescript-types", "skill-portfolio-evidence"]
    },
    {
      id: "mission-api-contract-playground",
      trackId: "track-typescript",
      title: "API Contract Playground",
      brief: "Model a tiny request/response contract and validate examples before UI consumes them.",
      difficulty: "applied",
      deliverables: ["Request and response types", "Validation examples", "Consumer rendering example"],
      acceptanceCriteria: ["Invalid examples fail clearly", "Consumer code reads narrowed data", "Tests cover one bad payload"],
      phases: missionPhases("api-contract-playground", "a validated API contract slice", "typecheck and validation tests"),
      starterPrompt: "Create TypeScript types and validation for a project mission API response, then render a small consumer view from parsed data.",
      verificationCommands: ["npm run typecheck", "npm test"],
      expectedArtifacts: ["Schema/type file", "Passing and failing examples", "Check output", "README contract notes"],
      rubric: ["Boundary validation is separate from rendering", "Bad payloads produce useful errors", "README names contract assumptions"],
      commonFailureModes: ["Trusting raw JSON as typed", "Letting UI validate everything", "No negative test case"],
      portfolioSummaryPrompt: "Describe the contract boundary and how validation prevents UI failure.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-typescript-types", "skill-api-contracts", "skill-testing-debugging"]
    },
    {
      id: "mission-sql-portfolio-ledger",
      trackId: "track-sql",
      title: "Portfolio Evidence Ledger",
      brief: "Design SQL tables for projects, evidence, skills, and readiness snapshots.",
      difficulty: "applied",
      deliverables: ["Schema sketch", "Three useful queries", "Known limitations note"],
      acceptanceCriteria: ["Missions can have multiple evidence items", "Skills can attach to lessons and projects", "A stale evidence query exists"],
      phases: missionPhases("sql-portfolio-ledger", "a normalized evidence ledger", "three saved SQL queries with expected rows"),
      starterPrompt: "Design a normalized SQL schema that connects projects, evidence items, skills, and readiness snapshots.",
      verificationCommands: ["sqlite3 evidence.db < schema.sql", "sqlite3 evidence.db < queries.sql"],
      expectedArtifacts: ["Schema SQL", "Seed data", "Three query outputs", "Limitations note"],
      rubric: ["Many-to-many skill evidence is modeled", "Queries answer product questions", "Known tradeoffs are explicit"],
      commonFailureModes: ["One giant table", "Queries with no sample output", "No stale or missing-evidence query"],
      portfolioSummaryPrompt: "Explain the product questions your schema can answer and why the table boundaries matter.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-sql-joins", "skill-portfolio-evidence"]
    },
    {
      id: "mission-job-tracker-schema",
      trackId: "track-sql",
      title: "Job Tracker Schema",
      brief: "Design a small job-application tracker schema with skill gaps and follow-up tasks.",
      difficulty: "portfolio",
      deliverables: ["Application schema", "Skill-gap query", "Follow-up query", "Seeded sample data"],
      acceptanceCriteria: ["Applications link to companies and required skills", "Query finds missing skills by role", "Follow-up dates are queryable"],
      phases: missionPhases("job-tracker-schema", "a job tracker data model", "schema load plus two product queries"),
      starterPrompt: "Create SQL tables for companies, applications, required skills, evidence links, and follow-up tasks.",
      verificationCommands: ["sqlite3 job_tracker.db < schema.sql", "sqlite3 job_tracker.db < sample_queries.sql"],
      expectedArtifacts: ["Schema SQL", "Seed rows", "Skill-gap output", "Follow-up output"],
      rubric: ["Skill gaps connect to evidence", "Queries support real job-search decisions", "README explains next migration"],
      commonFailureModes: ["Treating skills as comma-separated text", "No date handling", "No evidence link back to portfolio work"],
      portfolioSummaryPrompt: "Turn the schema into a resume bullet about backend data modeling for job-search workflows.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-sql-joins", "skill-api-contracts", "skill-portfolio-evidence"]
    },
    {
      id: "mission-portfolio-readme",
      trackId: "track-git",
      title: "Portfolio README Upgrade",
      brief: "Turn one practice repository README into a reviewer-friendly artifact.",
      difficulty: "foundation",
      deliverables: ["Problem statement", "Run commands", "Verification section", "Screenshot or sample output"],
      acceptanceCriteria: ["A new developer can run the project", "Verification claims include exact commands", "Known gaps are listed honestly"],
      phases: missionPhases("portfolio-readme", "a reviewer-ready README", "fresh setup and verification commands", "known-gaps section"),
      starterPrompt: "Choose one practice repo and rewrite the README so a reviewer can understand, run, verify, and judge the project quickly.",
      verificationCommands: ["git status --short", "run the repo's documented verifier"],
      expectedArtifacts: ["README diff", "Commit hash", "Screenshot or sample output", "Known gaps"],
      rubric: ["Setup works from a clean checkout", "Verification claims include exact commands", "Known gaps are honest and scoped"],
      commonFailureModes: ["Marketing copy without commands", "No screenshot or sample output", "No commit link"],
      portfolioSummaryPrompt: "Draft two portfolio bullets from the README's verified behavior.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-git-workflow", "skill-portfolio-evidence"]
    },
    {
      id: "mission-ai-bug-rubric",
      trackId: "track-ai-tools",
      title: "AI Bug Review Rubric",
      brief: "Create a small rubric for reviewing AI-suggested bug fixes before accepting them.",
      difficulty: "applied",
      deliverables: ["Rubric markdown", "Example accepted fix", "Example rejected fix"],
      acceptanceCriteria: ["Requires local reproduction or substitute evidence", "Requires check output", "Flags secret, auth, or public-contract risk"],
      phases: missionPhases("ai-bug-rubric", "an AI bug-review rubric", "rubric applied to two examples"),
      starterPrompt: "Write a rubric that decides whether an AI-suggested bug fix is safe to accept, then apply it to one accepted and one rejected example.",
      verificationCommands: ["markdownlint README.md or manual checklist", "run verifier for accepted example"],
      expectedArtifacts: ["Rubric markdown", "Accepted example", "Rejected example", "Check output"],
      rubric: ["Reproduction is required or explicitly substituted", "Security and contract risk are checked", "Rejected example explains the failure mode"],
      commonFailureModes: ["Accepting plausible code without evidence", "Ignoring public contract changes", "No rejected example"],
      portfolioSummaryPrompt: "Explain how this demonstrates AI-assisted engineering judgment rather than blind tool use.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-ai-verification", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-ai-test-harness",
      trackId: "track-ai-tools",
      title: "AI Prompt Verification Harness",
      brief: "Build a tiny harness that records prompt intent, model output, human edits, and check result.",
      difficulty: "portfolio",
      deliverables: ["Prompt log format", "Verifier script", "Before/after example", "Risk notes"],
      acceptanceCriteria: ["Separates model suggestion from accepted code", "Stores exact check result", "Flags hallucinated or unsafe suggestions"],
      phases: missionPhases("ai-test-harness", "an AI verification harness", "a sample run with passing and rejected outputs"),
      starterPrompt: "Create a small local workflow that captures an AI suggestion, the human-edited final version, and the check output that justified accepting it.",
      verificationCommands: ["npm run test", "node scripts/verify-ai-suggestion.js samples/example.json"],
      expectedArtifacts: ["Prompt log sample", "Verifier script", "Accepted output", "Rejected output"],
      rubric: ["Model output is treated as untrusted", "Accepted changes cite verifier evidence", "Unsafe output is visibly rejected"],
      commonFailureModes: ["Saving only the final answer", "No negative example", "No exact command output"],
      portfolioSummaryPrompt: "Summarize the harness as proof of responsible AI-assisted development.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-ai-verification", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-ai-study-planner",
      trackId: "track-ai-apps",
      title: "AI Study Planner Boundary Map",
      brief: "Design a future AI mentor flow without client-side secrets or fake certainty.",
      difficulty: "applied",
      deliverables: ["Request flow", "Server boundary list", "Evaluation questions"],
      acceptanceCriteria: ["No model secrets live in the app", "Plan records uncertainty", "Output requires evidence before changing readiness"],
      phases: missionPhases("ai-study-planner", "an AI study-planner boundary map", "manual threat and eval checklist"),
      starterPrompt: "Map the request flow for a future AI mentor that suggests weekly study work without storing vendor secrets in the mobile bundle.",
      verificationCommands: ["review the boundary checklist", "review the eval questions against one sample output"],
      expectedArtifacts: ["Request-flow diagram", "Server boundary list", "Evaluation checklist", "Uncertainty notes"],
      rubric: ["Secrets stay server-side", "Readiness changes require evidence", "Output confidence is not overstated"],
      commonFailureModes: ["Putting API keys in the app", "Letting AI update readiness directly", "No eval questions"],
      portfolioSummaryPrompt: "Explain the security boundary and evaluation method in portfolio language.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-ai-verification", "skill-api-contracts"]
    },
    {
      id: "mission-rag-notes-prototype",
      trackId: "track-ai-apps",
      title: "RAG Notes Search Prototype",
      brief: "Prototype a local notes search flow that separates retrieval, answer generation, and verification.",
      difficulty: "portfolio",
      deliverables: ["Tiny notes corpus", "Retrieval function", "Answer-with-citations example", "Failure-case note"],
      acceptanceCriteria: ["Answer cites retrieved notes", "Unknown questions do not invent facts", "Verifier checks at least one citation"],
      phases: missionPhases("rag-notes-prototype", "a RAG notes prototype", "retrieval tests and citation checks"),
      starterPrompt: "Build a small notes search prototype that retrieves relevant notes, drafts an answer using only those notes, and rejects unsupported claims.",
      verificationCommands: ["npm run test", "node scripts/check-citations.js samples/rag-answer.json"],
      expectedArtifacts: ["Notes corpus", "Retrieval test output", "Cited answer", "Unsupported-question example"],
      rubric: ["Retrieval and generation are separate", "Unsupported answers fail closed", "Citations can be checked"],
      commonFailureModes: ["Answering from general knowledge", "No unsupported-question test", "No citation mapping"],
      portfolioSummaryPrompt: "Frame this as an AI app prototype with retrieval discipline and hallucination controls.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-ai-verification", "skill-api-contracts", "skill-portfolio-evidence"]
    },
    {
      id: "mission-ml-metrics-report",
      trackId: "track-ml",
      title: "ML Metrics Report",
      brief: "Evaluate a toy classifier and write a model-card style report with limits and failure cases.",
      difficulty: "applied",
      deliverables: ["Train/test split note", "Metrics table", "Failure-case examples", "Model-card summary"],
      acceptanceCriteria: ["Names the metric and sample size", "Shows at least one failure case", "Does not overclaim model quality"],
      phases: missionPhases("ml-metrics-report", "an ML metrics report", "metric reproduction and failure-case review"),
      starterPrompt: "Use a toy classifier result to write a short metrics report that explains the split, metric, sample size, and failure cases.",
      verificationCommands: ["python evaluate.py", "python -m pytest tests/test_metrics.py"],
      expectedArtifacts: ["Metrics output", "Failure examples", "Model-card note", "Check output"],
      rubric: ["Metric context is clear", "Failures are analyzed", "Claims are bounded by the data"],
      commonFailureModes: ["Reporting accuracy alone", "No holdout/split note", "No failure examples"],
      portfolioSummaryPrompt: "Summarize this as practical ML evaluation literacy for SWE work.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-ml-metrics", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-regression-proof-pack",
      trackId: "track-testing-debugging",
      title: "Regression Proof Pack",
      brief: "Create a small regression harness and failure log that prove a fixed bug stays fixed.",
      difficulty: "foundation",
      deliverables: ["Regression harness", "Normal and old-bug cases", "Failure log", "Check output"],
      acceptanceCriteria: ["Harness includes a happy path and rejected case", "Failure log names symptom, hypothesis, fix, verifier, and residual risk", "README explains what the harness does and does not prove"],
      phases: missionPhases("regression-proof-pack", "a regression proof pack", "a two-case harness and failure-log review"),
      starterPrompt: "Build a tiny verifier for one fixed behavior, add one old-bug case, and write a debugging log that explains the fix and remaining risk.",
      verificationCommands: ["node regression_harness.js", "review failure-log.md"],
      expectedArtifacts: ["Harness code", "Passing check output", "failure-log.md", "README proof section"],
      rubric: ["The rejected case would catch the old bug", "Check output is exact", "Failure log is specific enough for another person to review"],
      commonFailureModes: ["Only testing the happy path", "Writing a vague failure log", "Claiming broad quality from one tiny harness"],
      portfolioSummaryPrompt: "Explain how this proves testing and debugging discipline before specialization.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-testing-debugging", "skill-regression-testing", "skill-debugging-log", "skill-portfolio-evidence"]
    },
    {
      id: "mission-secure-review-pack",
      trackId: "track-secure-software",
      title: "Secure Review Pack",
      brief: "Review a small app feature for threats, secrets, auth boundaries, input validation, dependency risk, and safe logging.",
      difficulty: "portfolio",
      deliverables: ["Threat table", "Config and secret classification", "Auth-boundary note", "Input validation tests", "Dependency/logging checklist", "Residual-risk summary"],
      acceptanceCriteria: ["Every threat has a control and verifier", "Secrets are separated from public config", "Auth is enforced at a server/data boundary", "Input validation has a negative test", "Dependency and logging risks are classified before release"],
      phases: missionPhases("secure-review-pack", "a secure review pack", "validation tests plus security checklist review", "portfolio security note"),
      starterPrompt: "Choose one small feature and build a security review pack that maps threats to controls, verifies validation behavior, and documents release hygiene.",
      verificationCommands: ["npm run test", "review security-checklist.md", "review config-classification.md"],
      expectedArtifacts: ["Threat table", "Validation test output", "Config classification", "Dependency/logging checklist", "Residual-risk note", "README security section"],
      rubric: ["Risks are feature-specific", "Controls map to verifiers", "Secrets and auth boundaries are explicit", "Validation rejects malformed input", "Residual risk is honest"],
      commonFailureModes: ["Generic security claims", "No negative validation test", "Client-side-only authorization", "Logging sensitive values", "No residual-risk note"],
      portfolioSummaryPrompt: "Explain how this demonstrates entry-level AppSec judgment with evidence-backed controls.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-threat-modeling", "skill-secret-handling", "skill-auth-boundaries", "skill-dependency-hygiene", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-cloud-release-runbook",
      trackId: "track-cloud-platform-basics",
      title: "Cloud Release Runbook",
      brief: "Create a beginner cloud release runbook with config, CI checks, logs, cost note, and rollback plan.",
      difficulty: "applied",
      deliverables: ["Environment config matrix", "Release gate checklist", "Post-deploy ops note", "Rollback note"],
      acceptanceCriteria: ["Config matrix separates public settings from secrets", "Release gate blocks missing build, tests, or rollback", "Ops note includes log health and cost signal", "Rollback action is concrete"],
      phases: missionPhases("cloud-release-runbook", "a cloud release runbook", "config and release-gate checks"),
      starterPrompt: "Prepare a release runbook for a small app that documents required environment variables, CI checks, post-deploy monitoring, cost assumptions, and rollback action.",
      verificationCommands: ["review env-matrix.md", "review release-gate.md", "review ops-note.md"],
      expectedArtifacts: ["env-matrix.md", "release-gate.md", "ops-note.md", "rollback note", "Check output"],
      rubric: ["Secret handling is explicit", "Deploy readiness is gated by named checks", "Operations note includes health and cost", "Rollback is actionable"],
      commonFailureModes: ["Committing secret values", "Treating build success as the only release gate", "No cost or rollback note", "No evidence after deploy"],
      portfolioSummaryPrompt: "Frame this as cloud platform readiness: deployable work with evidence, budget awareness, and recovery planning.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-cloud-config", "skill-ci-release", "skill-observability-cost", "skill-portfolio-evidence"]
    },
    {
      id: "mission-data-quality-report",
      trackId: "track-data-systems",
      title: "Data Quality Report",
      brief: "Build a small data-quality report with accepted/rejected rows, lineage, reproducible output, and limitations.",
      difficulty: "applied",
      deliverables: ["Quality rules", "Rejected-row report", "Pipeline lineage map", "Reproducible report note", "Limitations section"],
      acceptanceCriteria: ["Bad records are rejected with reasons", "Lineage traces source to output", "Report can be rerun from named inputs", "Limitations are stated next to the result"],
      phases: missionPhases("data-quality-report", "a data quality report", "row validation and reproducible report checks"),
      starterPrompt: "Create a small report pipeline for learning events that validates input rows, maps lineage, and produces a rerunnable weekly summary with limitations.",
      verificationCommands: ["node validate_rows.js", "review lineage.md", "review report-note.md"],
      expectedArtifacts: ["Quality rules", "Rejected rows", "Lineage map", "Report output", "Limitations note", "Check output"],
      rubric: ["Rejected rows explain the reason", "Lineage is traceable", "Report input version and query logic are named", "Limitations prevent overclaiming"],
      commonFailureModes: ["Dropping rows silently", "No source-to-output lineage", "One-off screenshot as report proof", "No limitations"],
      portfolioSummaryPrompt: "Explain how this demonstrates data systems thinking for backend and product-facing work.",
      evidenceRequirements: foundationEvidence,
      skillIds: ["skill-data-quality", "skill-data-pipelines", "skill-reproducible-report", "skill-portfolio-evidence"]
    },
    {
      id: "mission-python-api-resilience",
      trackId: "track-python",
      title: "Resilient API Integration",
      brief: "Build a resilient API client with retry, exponential backoff, caching, and circuit breaker patterns for the Study Tracker.",
      difficulty: "portfolio",
      deliverables: ["Retry wrapper with max_retries", "Exponential backoff for 429 rate limits", "In-memory response cache with TTL", "Circuit breaker with open/half-open/closed states", "Integration tests for all patterns", "Architecture note explaining pattern choices"],
      acceptanceCriteria: ["Retry handles 503 errors up to max_retries", "Backoff doubles delay after 429 and caps at max_delay", "Cache returns data without network call on repeated URLs", "Circuit breaker opens after threshold failures and recovers via half-open", "Each pattern has passing unit tests", "Architecture note names trade-offs of each pattern"],
      phases: missionPhases("python-api-resilience", "a resilient API integration layer", "unit tests for retry, backoff, cache, and circuit breaker", "portfolio architecture note"),
      starterPrompt: "Extend the Study Tracker API client with retry, exponential backoff, caching, and circuit breaker patterns. Each pattern should be independently testable and documented with its trade-offs.",
      verificationCommands: ["python -m pytest", "python -m pytest tests/test_retry.py", "python -m pytest tests/test_rate_limit.py", "python -m pytest tests/test_caching.py", "python -m pytest tests/test_circuit_breaker.py"],
      expectedArtifacts: ["Retry wrapper code", "Backoff implementation", "Cache implementation", "Circuit breaker class", "Test output for all four patterns", "Architecture note"],
      rubric: ["Each pattern solves a distinct problem", "Patterns compose correctly (retry uses backoff, circuit wraps retry)", "Tests prove both success and failure paths", "Architecture note explains when each pattern applies"],
      commonFailureModes: ["Retry does not stop on 200", "Backoff uses fixed delay instead of exponential", "Cache stores error responses", "Circuit breaker never transitions to half-open", "Integration tests only cover the happy path"],
      portfolioSummaryPrompt: "Explain how the four resilience patterns work together to make the API client production-ready, including the trade-offs you considered.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-python-integration", "skill-api-contracts", "skill-testing-debugging", "skill-portfolio-evidence"]
    },
    {
      id: "mission-python-ops",
      trackId: "track-python",
      title: "Production Readiness",
      brief: "Deploy a monitored, secure Study Tracker application with CI/CD, secrets management, deployment strategy, and health monitoring.",
      difficulty: "portfolio",
      deliverables: ["CI workflow file with lint and test gates", "Secrets dataclass with from_env boundary", "Deployment runbook with strategy and rollback", "Health check endpoint specification", "Structured logging configuration", "Monitoring and alert thresholds document"],
      acceptanceCriteria: ["CI workflow triggers on push and pull_request", "Secrets boundary loads from environment with no defaults for required values", "Deployment runbook names strategy, health check, rollback command, and monitor window", "Health check reports dependency status", "Logs are structured JSON with event and severity fields", "Alert thresholds are documented with action owners"],
      phases: missionPhases("python-ops", "a production-ready deployment pipeline", "CI check, secrets tests, and runbook review", "portfolio README"),
      starterPrompt: "Prepare the Study Tracker for production: set up CI, secure secrets, define a deployment strategy with health checks, and configure monitoring and alerting.",
      verificationCommands: ["python -m pytest", "review secrets boundary", "review deployment runbook", "review health check specification"],
      expectedArtifacts: [".github/workflows/ci.yml", "Secrets dataclass", "Deployment runbook", "Health check spec", "Structured log example", "Alert thresholds document", "README"],
      rubric: ["CI gates deployment behind passing tests", "Secrets are never hardcoded or printed in plain text", "Deployment strategy includes health check verification", "Monitoring captures both success and error events", "Alert thresholds have clear action owners"],
      commonFailureModes: ["CI deploys without test gate", "Secrets use default fallback values", "Deployment runbook skips rollback plan", "Health check always returns ok regardless of dependencies", "No alert thresholds defined", "README claims readiness without evidence"],
      portfolioSummaryPrompt: "Explain how this project demonstrates production readiness: automated verification, secret safety, deployment discipline, and operational observability.",
      evidenceRequirements: portfolioEvidence,
      skillIds: ["skill-python-professional", "skill-secret-handling", "skill-ci-release", "skill-testing-debugging", "skill-portfolio-evidence"]
    }
  ],
  weeklyPlan: {
    id: "weekly-plan-2026-05-04",
    weekStart: "2026-05-04",
    headline: "Build evidence, not just streaks.",
    tasks: [
      {
        id: "task-python-cli",
        title: "Ship one Python utility",
        detail: "Complete the CLI Study Tracker mission and capture command output.",
        linkedProjectMissionId: "mission-cli-study-tracker",
        minutes: 90
      },
      {
        id: "task-git-readme",
        title: "Upgrade one README",
        detail: "Add setup, verification, and known gaps to a small practice repo.",
        linkedProjectMissionId: "mission-portfolio-readme",
        minutes: 45
      },
      {
        id: "task-ai-loop",
        title: "Practice AI verification",
        detail: "Use AI for one test idea, then keep only the locally verified result.",
        linkedProjectMissionId: "mission-ai-test-harness",
        minutes: 60
      },
      {
        id: "task-schema-depth",
        title: "Deepen one data model",
        detail: "Complete one schema mission and capture the query output that proves it.",
        linkedProjectMissionId: "mission-job-tracker-schema",
        minutes: 75
      }
    ]
  }
};
