import { normalizeCodeRunAttempt, redactCheckResults } from "@/domain/code-run";
import type { CodeRunAttempt, CodeRunMode, LessonRunnerSpec, RunnerLanguage } from "@/domain/types";
import {
  PYTHON_DIRECT_RUN_NAME,
  PYTHON_IMPORT_RUN_NAME,
  SQL_HARNESS_DANGEROUS_PATTERN,
  SQL_HARNESS_PATTERN,
  isTrustedSqlHarness
} from "./runner";
import { TYPESCRIPT_MAX_SOURCE_CHARS, TYPESCRIPT_TYPE_CHECK_SOURCE } from "./typescript-typecheck";

export interface NativeWebViewRunnerRequest {
  lessonId: string;
  spec: LessonRunnerSpec;
  code: string;
  now: string;
  runMode: CodeRunMode;
}

export const SANDBOX_ASSET_PATHS = {
  pyodide: "file:///android_asset/sandbox-assets/pyodide/",
  sqlJs: "file:///android_asset/sandbox-assets/sql.js/",
  typescript: "file:///android_asset/sandbox-assets/typescript/"
} as const;

export const NATIVE_ANDROID_SANDBOX_BASE_URL = "file:///android_asset/";

const NATIVE_RUNTIME_ASSET_LANGUAGES = ["python", "sql", "typescript"] as const;

/**
 * Extra wall-clock time granted on top of a lesson's `timeoutMs` for the first
 * run in a session, covering the cost of loading a large sandbox runtime into
 * the WebView. Python (Pyodide), SQL (sql.js), and TypeScript all load a bundled
 * asset, so all three need the allowance: TypeScript loads an ~9 MB compiler,
 * heavier than sql.js and comparable to Pyodide. A learner should not see a
 * spurious timeout because the runtime was still parsing.
 *
 * Status: this is a flat, deliberately generous ceiling. The ~4250 ms device
 * cold-start figure often quoted for the TypeScript asset has not been measured
 * on a physical device, so treat 20 s as an unvalidated upper bound rather than
 * a measured budget. Do not lower it without device timing evidence.
 */
export const NATIVE_RUNTIME_STARTUP_ALLOWANCE_MS = 20000;
export const NATIVE_DEFAULT_STARTUP_ALLOWANCE_MS = 250;

/** Resolve the startup allowance a native run gets for its language runtime. */
export function nativeStartupAllowanceMs(language: RunnerLanguage): number {
  return (NATIVE_RUNTIME_ASSET_LANGUAGES as readonly string[]).includes(language)
    ? NATIVE_RUNTIME_STARTUP_ALLOWANCE_MS
    : NATIVE_DEFAULT_STARTUP_ALLOWANCE_MS;
}

/**
 * Resolve the wall-clock timeout for a native run. The startup allowance is
 * granted only while the language runtime is still cold: once the WebView has
 * reported (via the `sandbox-warm` preload handshake) that the runtime is
 * loaded, later runs get the lesson's plain `timeoutMs`. Without this gate a
 * session that preloaded `typescript` would keep 20 s of slack on every run,
 * masking a genuinely runaway submission.
 */
export function nativeRunTimeoutMs(timeoutMs: number, language: RunnerLanguage, isRuntimeWarm: boolean): number {
  return isRuntimeWarm ? timeoutMs : timeoutMs + nativeStartupAllowanceMs(language);
}

/**
 * Exported test seam. The native runtime path does not call this wrapper: the
 * embedded script generated by `createNativeWebViewRunnerHtml` mirrors the gate
 * inline, and the web runtime calls `isTrustedSqlHarness` directly. Tests use
 * this alias to prove the native and web predicates stay identical.
 */
export function nativeWebViewTrustedSqlHarness(code: string): boolean {
  return isTrustedSqlHarness(code);
}

export interface NativeWebViewRunnerReadyMessage {
  type: "sandbox-ready";
  assets: typeof SANDBOX_ASSET_PATHS;
}

export interface NativeWebViewRunnerResultMessage {
  type: "sandbox-result";
  attempt: CodeRunAttempt;
}

export interface NativeWebViewRunnerWarmMessage {
  type: "sandbox-warm";
  language: RunnerLanguage;
}

export type NativeWebViewRunnerMessage =
  | NativeWebViewRunnerReadyMessage
  | NativeWebViewRunnerResultMessage
  | NativeWebViewRunnerWarmMessage;

export function createNativeWebViewRunnerHtml(): string {
  return `<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>ProofPath Sandbox Runner</title>
</head>
<body>
  <script>
    window.PROOFPATH_SANDBOX_ASSETS = ${JSON.stringify(SANDBOX_ASSET_PATHS)};
    // Mirrors TYPESCRIPT_MAX_SOURCE_CHARS in src/sandbox/typescript-typecheck.ts.
    // The type check runs synchronously on the main thread, so a huge submission
    // is rejected before the compiler asset is loaded rather than freezing the UI.
    const TYPESCRIPT_MAX_SOURCE_CHARS = ${TYPESCRIPT_MAX_SOURCE_CHARS};
    // Shared with the web runner (src/sandbox/runner.ts) so the two runners
    // cannot drift on Python run-mode fidelity or SQL harness gating.
    const PYTHON_DIRECT_RUN_NAME = ${JSON.stringify(PYTHON_DIRECT_RUN_NAME)};
    const PYTHON_IMPORT_RUN_NAME = ${JSON.stringify(PYTHON_IMPORT_RUN_NAME)};
    const SQL_HARNESS_PATTERN = new RegExp(${JSON.stringify(SQL_HARNESS_PATTERN.source)}, "i");
    const SQL_HARNESS_DANGEROUS_PATTERN = new RegExp(${JSON.stringify(SQL_HARNESS_DANGEROUS_PATTERN.source)}, "i");
    /* trusted-sql-harness-gate:start */
    // Mirrors src/sandbox/runner.ts isTrustedSqlHarness so the web and native
    // runners cannot drift on which trusted harness SQL executes.
    function stripSqlLiteralsAndComments(code) {
      let sanitized = "";
      let index = 0;
      const blankChar = (char) => (char === "\\n" ? "\\n" : " ");
      while (index < code.length) {
        const char = code[index];
        const next = code[index + 1];
        if (char === "-" && next === "-") {
          sanitized += "  ";
          index += 2;
          while (index < code.length && code[index] !== "\\n") {
            sanitized += " ";
            index += 1;
          }
          continue;
        }
        if (char === "/" && next === "*") {
          sanitized += "  ";
          index += 2;
          while (index < code.length) {
            if (code[index] === "*" && code[index + 1] === "/") {
              sanitized += "  ";
              index += 2;
              break;
            }
            sanitized += blankChar(code[index]);
            index += 1;
          }
          continue;
        }
        const quote = char === "'" ? "'" : char === '"' ? '"' : char === "\`" ? "\`" : char === "[" ? "]" : null;
        if (quote) {
          const escapeDoubled = quote !== "]";
          sanitized += " ";
          index += 1;
          while (index < code.length) {
            if (code[index] === quote) {
              if (escapeDoubled && code[index + 1] === quote) {
                sanitized += "  ";
                index += 2;
                continue;
              }
              sanitized += " ";
              index += 1;
              break;
            }
            sanitized += blankChar(code[index]);
            index += 1;
          }
          continue;
        }
        sanitized += char;
        index += 1;
      }
      return sanitized;
    }

    function isTrustedSqlHarness(code) {
      if (!SQL_HARNESS_PATTERN.test(code)) return false;
      const stripped = stripSqlLiteralsAndComments(code);
      if (SQL_HARNESS_DANGEROUS_PATTERN.test(stripped)) return false;
      const statements = stripped.split(";");
      for (let i = 0; i < statements.length; i += 1) {
        const statement = statements[i].trim();
        if (statement.length > 0 && !/^(SELECT|WITH|INSERT|CREATE)\\b/i.test(statement)) {
          return false;
        }
      }
      return true;
    }
    /* trusted-sql-harness-gate:end */
    /* typescript-typecheck:start */
    // Shared with the web runner (src/sandbox/typescript-typecheck.ts) so a type
    // error fails a check identically in the browser and the native WebView.
    ${TYPESCRIPT_TYPE_CHECK_SOURCE}
    /* typescript-typecheck:end */
    function post(payload) {
      window.ReactNativeWebView && window.ReactNativeWebView.postMessage(JSON.stringify(payload));
    }

    function normalizeOutput(value) {
      if (value === undefined || value === null) return "";
      if (typeof value === "string") return value;
      return JSON.stringify(value);
    }

    function stripTypeScript(code) {
      return code
        .replace(/type\\s+\\w+\\s*=\\s*\\{[\\s\\S]*?\\};/g, "")
        .replace(/interface\\s+\\w+\\s*\\{[\\s\\S]*?\\}/g, "")
        .replace(/:\\s*[A-Za-z_$][A-Za-z0-9_$<>,\\s[\\]|]*(?=\\s*[=,);])/g, "");
    }

    function includesAll(output, needles) {
      const normalizedOutput = output.toLowerCase();
      return (needles || []).every((needle) => normalizedOutput.includes(String(needle).toLowerCase()));
    }

    function outputHasExactLines(output, expectedLines) {
      const lines = new Set(
        output.split("\\n").map(function (line) { return line.trim().toLowerCase(); }).filter(Boolean)
      );
      return (expectedLines || []).every(function (expected) { return lines.has(String(expected).trim().toLowerCase()); });
    }

    function passesOutputCheck(output, test) {
      return test.expectedOutputExactLines && test.expectedOutputExactLines.length > 0
        ? outputHasExactLines(output, test.expectedOutputExactLines)
        : includesAll(output, test.expectedOutputIncludes);
    }

    function classifySandboxError(error) {
      const message = error instanceof Error ? error.message : String(error || "");
      if (/output missing/i.test(message)) return "missing-output";
      if (/timed out|timeout/i.test(message)) return "timeout";
      return "runtime";
    }

    function formatSandboxFailureMessage(error, language) {
      const kind = classifySandboxError(error);
      const detail = error instanceof Error ? error.message : String(error || "Test failed");
      const label = language === "typescript"
        ? "TypeScript"
        : language === "javascript"
          ? "JavaScript"
          : language === "python"
            ? "Python"
            : "SQL";

      if (kind === "missing-output") {
        return [
          "Not yet. The test ran, but it did not see all of the proof it was looking for.",
          "Think through your " + label + " flow: where is the required value produced, and where is it printed or returned?",
          "Before changing a lot, compare your output with the expected lines. Check for starter values left unchanged, quotes around numbers, empty summaries, and missing print calls."
        ].join("\\n");
      }

      if (kind === "timeout") {
        return [
          "The runner stopped because the code took too long.",
          "This lesson may not need a loop, input(), recursion, or repeated step. Remove any code that keeps waiting or repeating after the answer is already known.",
          "If the lesson does ask for a loop, name the stopping condition in plain English, then make the code match that condition."
        ].join("\\n");
      }

      return [
        "The code crashed before the test could finish checking it.",
        "Read the first " + label + " error clue, then ask: which name, value, or line is the program complaining about?",
        "Error clue: " + detail,
        "Make the smallest change that would prove your next assumption, then run the test again."
      ].join("\\n");
    }

    function formatRunnerFailureMessage(error, language) {
      return [
        "The sandbox runner could not finish this attempt.",
        "Is the starter code using the lesson language and the visible test shape shown on screen?",
        "Runner note: " + (error instanceof Error ? error.message : String(error || "No extra detail was reported."))
      ].join("\\n");
    }

    function buildAttempt(request, startedAt, stdout, stderr, testResults) {
      const passedTests = testResults.filter((result) => result.passed).length;
      const score = testResults.length === 0 ? 0 : Math.round((passedTests / testResults.length) * 100);
      // Mirror the web runner: a run_file attempt is only passed when it produced
      // no error output (a raised exception lands in stderr). Checks still require
      // every result to pass.
      const passed = request.runMode === "run_file"
        ? stderr.join("\\n").trim().length === 0
        : testResults.length > 0 && testResults.every((result) => result.passed);
      const redacted = redactCheckResults(testResults);
      const learnerSafeHiddenSummary = { total: 0, passed: 0, failed: 0 };

      return {
        id: "code-run-" + request.lessonId + "-" + request.now.replace(/[^0-9]/g, ""),
        lessonId: request.lessonId,
        language: request.spec.language,
        runMode: request.runMode || "run_checks",
        codeSnapshot: request.code,
        stdout: stdout.join("\\n"),
        stderr: stderr.join("\\n"),
        passed,
        score,
        runtimeMs: Date.now() - startedAt,
        testResults: redacted.visibleCheckResults,
        hiddenCheckSummary: learnerSafeHiddenSummary,
        createdAt: request.now
      };
    }

    function redactCheckResults(testResults) {
      const visibleCheckResults = testResults
        .filter((result) => result.visible)
        .map((result) => ({ ...result, visible: true }));
      const hiddenResults = testResults.filter((result) => !result.visible);

      return {
        visibleCheckResults,
        hiddenCheckSummary: {
          total: hiddenResults.length,
          passed: hiddenResults.filter((result) => result.passed).length,
          failed: hiddenResults.filter((result) => !result.passed).length
        }
      };
    }

    let typeScriptRuntime = null;
    async function getTypeScriptRuntime() {
      if (typeScriptRuntime) return typeScriptRuntime;

      if (!window.ts) {
        await loadScript(window.PROOFPATH_SANDBOX_ASSETS.typescript + "typescript.js");
      }

      if (!window.ts) {
        throw new Error("TypeScript compiler asset loaded without ts.");
      }

      if (!window.PROOFPATH_TYPESCRIPT_LIBS) {
        await loadScript(window.PROOFPATH_SANDBOX_ASSETS.typescript + "typescript-libs.js");
      }

      if (!window.PROOFPATH_TYPESCRIPT_LIBS) {
        throw new Error("TypeScript library assets loaded without libs.");
      }

      typeScriptRuntime = window.ts;
      return typeScriptRuntime;
    }

    async function runTypeScriptTypeCheck(code) {
      const ts = await getTypeScriptRuntime();
      return proofPathTypeCheck(ts, window.PROOFPATH_TYPESCRIPT_LIBS, "lesson.ts", code);
    }

    async function runJavaScriptLike(request) {
      const startedAt = Date.now();
      const spec = request.spec;
      const stdout = [];
      const stderr = [];
      const testResults = [];
      const tests = spec.visibleTests.concat(spec.hiddenTests || []);
      const sandboxConsole = {
        log: (...values) => stdout.push(values.map(normalizeOutput).join(" ")),
        error: (...values) => stderr.push(values.map(normalizeOutput).join(" "))
      };

      // TypeScript lessons must fail on type errors, which stripping and running
      // the code can never detect. stripTypeScript is still used below, but only
      // to erase annotations before execution.
      if (spec.language === "typescript") {
        // Fail fast before loading the ~9 MB compiler for a pathologically large
        // submission: ts.createProgram is synchronous and cannot be preempted.
        if (request.code.length > TYPESCRIPT_MAX_SOURCE_CHARS) {
          throw new Error("TypeScript source is too large to type-check: " + request.code.length +
            " characters exceeds the " + TYPESCRIPT_MAX_SOURCE_CHARS + "-character limit.");
        }
        const typeCheck = await runTypeScriptTypeCheck(request.code);
        if (typeCheck.diagnostics.length > 0) {
          stderr.push(typeCheck.stderr);
          if (request.runMode === "run_file") {
            return buildAttempt(request, startedAt, stdout, stderr, testResults);
          }
          for (let index = 0; index < tests.length; index += 1) {
            testResults.push({
              id: tests[index].id,
              name: tests[index].name,
              passed: false,
              visible: index < spec.visibleTests.length,
              message: typeCheck.learnerMessage
            });
          }
          return buildAttempt(request, startedAt, stdout, stderr, testResults);
        }
      }

      const runtimeCode = spec.language === "typescript" ? stripTypeScript(request.code) : request.code;

      if (request.runMode === "run_file") {
        try {
          const runner = new Function("console", "\\"use strict\\";\\n" + runtimeCode);
          runner(sandboxConsole);
        } catch (error) {
          stderr.push(error instanceof Error ? error.message : String(error));
        }
        return buildAttempt(request, startedAt, stdout, stderr, testResults);
      }

      for (let index = 0; index < tests.length; index += 1) {
        const test = tests[index];
        const visible = index < spec.visibleTests.length;
        const stdoutStart = stdout.length;

        try {
          const runner = new Function("console", "\\"use strict\\";\\n" + runtimeCode + "\\n" + test.code);
          runner(sandboxConsole);
          const output = stdout.slice(stdoutStart).join("\\n");
          if (!passesOutputCheck(output, test)) {
            throw new Error("Output missing");
          }
          testResults.push({ id: test.id, name: test.name, passed: true, visible, message: "Passed" });
        } catch (error) {
          testResults.push({
            id: test.id,
            name: test.name,
            passed: false,
            visible,
            message: formatSandboxFailureMessage(error, spec.language)
          });
        } finally {
          // Hidden check output must never reach learner-visible stdout.
          if (!visible) {
            stdout.length = stdoutStart;
          }
        }
      }

      return buildAttempt(request, startedAt, stdout, stderr, testResults);
    }

    const scriptPromises = {};
    function loadScript(src) {
      // Cache the in-flight promise so overlapping loads (a preload racing the
      // first run) share one load instead of the second caller seeing the
      // first's still-loading tag and resolving before the asset is usable.
      if (scriptPromises[src]) {
        return scriptPromises[src];
      }

      const promise = new Promise((resolve, reject) => {
        const script = document.createElement("script");
        script.async = true;
        script.dataset.proofpathSrc = src;
        script.src = src;
        script.onload = () => resolve();
        script.onerror = () => {
          script.remove();
          reject(new Error("Unable to load bundled sandbox asset: " + src));
        };
        document.head.appendChild(script);
      }).catch((error) => {
        // Allow a later attempt to retry after a transient load failure.
        delete scriptPromises[src];
        throw error;
      });

      scriptPromises[src] = promise;
      return promise;
    }

    let pyodideRuntime = null;
    let pyodideRuntimePromise = null;
    async function getPyodideRuntime() {
      if (pyodideRuntime) return pyodideRuntime;
      // Cache the in-flight promise, not just the resolved runtime: a run that
      // races the preload must share the one Pyodide boot instead of starting a
      // second instance.
      if (pyodideRuntimePromise) return pyodideRuntimePromise;

      const promise = (async function() {
        if (!window.loadPyodide) {
          await loadScript(window.PROOFPATH_SANDBOX_ASSETS.pyodide + "pyodide.js");
        }

        if (!window.loadPyodide) {
          throw new Error("Pyodide asset loaded without loadPyodide.");
        }

        pyodideRuntime = await window.loadPyodide({
          indexURL: window.PROOFPATH_SANDBOX_ASSETS.pyodide
        });
        return pyodideRuntime;
      })().catch(function(error) {
        // Allow a later attempt to retry after a transient boot failure.
        pyodideRuntimePromise = null;
        throw error;
      });

      pyodideRuntimePromise = promise;
      return promise;
    }

    async function runPython(request) {
      const startedAt = Date.now();
      const spec = request.spec;
      const pyodide = await getPyodideRuntime();
      const stdout = [];
      const stderr = [];
      const testResults = [];
      const tests = spec.visibleTests.concat(spec.hiddenTests || []);
      // Mirror the web runner: run_file executes as the direct entry module
      // ("__main__") so guarded if __name__ == "__main__" blocks run, while
      // checks use an import-style sentinel that guarantees a non-__main__ name.
      const moduleName = request.runMode === "run_file" ? PYTHON_DIRECT_RUN_NAME : PYTHON_IMPORT_RUN_NAME;

      pyodide.setStdout({ batched: (text) => stdout.push(text) });
      pyodide.setStderr({ batched: (text) => stderr.push(text) });
      pyodide.globals.set("__name__", moduleName);

      if (request.runMode === "run_file") {
        try {
          await pyodide.runPythonAsync(request.code);
        } catch (error) {
          stderr.push(error instanceof Error ? error.message : String(error));
        }
        return buildAttempt(request, startedAt, stdout, stderr, testResults);
      }

      for (let index = 0; index < tests.length; index += 1) {
        const test = tests[index];
        const visible = index < spec.visibleTests.length;
        const stdoutStart = stdout.length;

        try {
          const wrappedCode = [
            "_proofpath_globals = {'__builtins__': __builtins__, '__name__': " + JSON.stringify(moduleName) + "}",
            "exec(" + JSON.stringify(request.code) + ", _proofpath_globals)",
            "exec(" + JSON.stringify(test.code) + ", _proofpath_globals)"
          ].join("\\n");

          await pyodide.runPythonAsync(wrappedCode);
          const output = stdout.slice(stdoutStart).join("\\n");
          if (!passesOutputCheck(output, test)) {
            throw new Error("Output missing");
          }
          testResults.push({ id: test.id, name: test.name, passed: true, visible, message: "Passed" });
        } catch (error) {
          stderr.push(error instanceof Error ? error.message : String(error || "Test failed"));
          testResults.push({
            id: test.id,
            name: test.name,
            passed: false,
            visible,
            message: formatSandboxFailureMessage(error, spec.language)
          });
        } finally {
          // Hidden checks must never contribute to learner-visible stdout: their
          // harness can reveal the anti-forgery seed. Keep only visible output.
          if (!visible) {
            stdout.length = stdoutStart;
          }
        }
      }

      return buildAttempt(request, startedAt, stdout, stderr, testResults);
    }

    let sqlRuntime = null;
    let sqlRuntimePromise = null;
    async function getSqlRuntime() {
      if (sqlRuntime) return sqlRuntime;
      // See getPyodideRuntime: cache the in-flight promise so a run racing the
      // preload shares one sql.js initialization.
      if (sqlRuntimePromise) return sqlRuntimePromise;

      const promise = (async function() {
        if (!window.initSqlJs) {
          await loadScript(window.PROOFPATH_SANDBOX_ASSETS.sqlJs + "sql-wasm.js");
        }

        if (!window.initSqlJs) {
          throw new Error("sql.js asset loaded without initSqlJs.");
        }

        sqlRuntime = await window.initSqlJs({
          locateFile: (file) => window.PROOFPATH_SANDBOX_ASSETS.sqlJs + file
        });
        return sqlRuntime;
      })().catch(function(error) {
        // Allow a later attempt to retry after a transient boot failure.
        sqlRuntimePromise = null;
        throw error;
      });

      sqlRuntimePromise = promise;
      return promise;
    }

    async function runSql(request) {
      const startedAt = Date.now();
      const spec = request.spec;
      const SQL = await getSqlRuntime();
      const stdout = [];
      const stderr = [];
      const testResults = [];
      const tests = spec.visibleTests.concat(spec.hiddenTests || []);

      if (request.runMode === "run_file") {
        const fileDb = new SQL.Database();
        try {
          if (spec.setupCode) {
            fileDb.run(spec.setupCode);
          }

          const result = fileDb.exec(request.code);
          const output = result.flatMap((table) => table.values.map((row) => row.join(" | "))).join("\\n");
          stdout.push(output);
        } catch (error) {
          stderr.push(error instanceof Error ? error.message : String(error));
        } finally {
          fileDb.close();
        }
        return buildAttempt(request, startedAt, stdout.filter(Boolean), stderr, testResults);
      }

      for (let index = 0; index < tests.length; index += 1) {
        const test = tests[index];
        const visible = index < spec.visibleTests.length;
        // Each check gets a fresh database seeded by setupCode so learner
        // scripts cannot leak state (for example a CREATE TABLE) into later
        // checks, and so a hidden harness seed cannot affect a visible check.
        const db = new SQL.Database();

        try {
          if (spec.setupCode) {
            db.run(spec.setupCode);
          }

          // A check's code is trusted harness SQL (like setupCode): it runs
          // against the freshly seeded database before the learner query and is
          // gated to seed-safe statements by the shared isTrustedSqlHarness gate.
          if (test.code && isTrustedSqlHarness(test.code)) {
            db.run(test.code);
          }

          const result = db.exec(request.code);
          const output = result.flatMap((table) => table.values.map((row) => row.join(" | "))).join("\\n");
          // Hidden checks must never contribute to learner-visible stdout: their
          // output reveals the anti-forgery seed inserted by the harness.
          if (visible) {
            stdout.push(output);
          }

          if (!passesOutputCheck(output, test)) {
            throw new Error("Output missing");
          }
          testResults.push({ id: test.id, name: test.name, passed: true, visible, message: output || "Query ran" });
        } catch (error) {
          stderr.push(error instanceof Error ? error.message : String(error || "Test failed"));
          testResults.push({
            id: test.id,
            name: test.name,
            passed: false,
            visible,
            message: formatSandboxFailureMessage(error, spec.language)
          });
        } finally {
          db.close();
        }
      }

      return buildAttempt(request, startedAt, stdout.filter(Boolean), stderr, testResults);
    }

    function runnerErrorAttempt(request, error) {
      const rawError = error instanceof Error ? error.message : String(error || "No extra detail was reported.");
      const guidance = request.runMode === "run_file" ? rawError : formatRunnerFailureMessage(error, request.spec.language);
      return {
        id: "code-run-" + request.lessonId + "-" + request.now.replace(/[^0-9]/g, ""),
        lessonId: request.lessonId,
        language: request.spec.language,
        runMode: request.runMode || "run_checks",
        codeSnapshot: request.code,
        stdout: "",
        stderr: guidance,
        passed: false,
        score: 0,
        runtimeMs: 0,
        testResults: request.runMode === "run_file" ? [] : [{ id: "native-webview-runner-error", name: "Native WebView runner", passed: false, visible: true, message: guidance }],
        createdAt: request.now
      };
    }

    async function handleRun(request) {
      let attempt;
      try {
        if (request.spec.language === "python") {
          attempt = await runPython(request);
        } else if (request.spec.language === "sql") {
          attempt = await runSql(request);
        } else {
          attempt = await runJavaScriptLike(request);
        }
      } catch (error) {
        attempt = runnerErrorAttempt(request, error);
      }

      post({ type: "sandbox-result", attempt });
    }

    function preloadRuntime(language) {
      // Warm the bundled asset before the first timed run so a cold 9 MB
      // TypeScript parse does not race the per-run allowance.
      var warmPromise = null;
      if (language === "typescript") {
        warmPromise = getTypeScriptRuntime();
      } else if (language === "python") {
        warmPromise = getPyodideRuntime();
      } else if (language === "sql") {
        warmPromise = getSqlRuntime();
      }

      if (!warmPromise) {
        return;
      }

      // Report once the runtime is actually usable. The host drops the
      // cold-start allowance only after this handshake, so a run racing a
      // still-loading preload keeps its allowance while later runs do not.
      warmPromise.then(function() {
        post({ type: "sandbox-warm", language: language });
      }).catch(function() {});
    }

    function handleMessage(event) {
      const payload = typeof event.data === "string" ? JSON.parse(event.data) : event.data;
      if (payload && payload.type === "run") {
        handleRun(payload.request);
      } else if (payload && payload.type === "preload") {
        preloadRuntime(payload.language);
      }
    }

    window.ProofPathSandbox = {
      run: function(payload) {
        handleMessage({ data: payload });
      },
      preload: function(payload) {
        handleMessage({ data: { type: "preload", language: payload.language } });
      }
    };

    window.addEventListener("message", handleMessage);
    document.addEventListener("message", handleMessage);

    post({
      type: "sandbox-ready",
      assets: window.PROOFPATH_SANDBOX_ASSETS
    });
  </script>
</body>
</html>`;
}

export function parseNativeWebViewRunnerMessage(payload: string): NativeWebViewRunnerMessage | null {
  try {
    const parsed = JSON.parse(payload) as {
      type?: string;
      assets?: typeof SANDBOX_ASSET_PATHS;
      attempt?: CodeRunAttempt;
      language?: RunnerLanguage;
    };

    if (parsed.type === "sandbox-ready" && parsed.assets) {
      return { type: "sandbox-ready", assets: parsed.assets };
    }

    if (parsed.type === "sandbox-warm" && typeof parsed.language === "string") {
      return { type: "sandbox-warm", language: parsed.language };
    }

    if (parsed.type === "sandbox-result" && parsed.attempt) {
      const redacted = redactCheckResults(parsed.attempt.testResults ?? []);
      return {
        type: "sandbox-result",
        attempt: normalizeCodeRunAttempt({
          ...parsed.attempt,
          testResults: redacted.visibleCheckResults,
          hiddenCheckSummary: redacted.hiddenCheckSummary
        })
      };
    }

    return null;
  } catch {
    return null;
  }
}

export function parseNativeWebViewRunnerResult(payload: string): CodeRunAttempt | null {
  const parsed = parseNativeWebViewRunnerMessage(payload);
  return parsed?.type === "sandbox-result" ? parsed.attempt : null;
}
